// apps/docs/src/react/DemoPage.tsx
import type { ReactNode } from 'react'
import { SECTIONS, type SectionKey } from '../site'

/**
 * Every page, the same shape: the sections it has, in the one order, each a
 * grid of specimens. A page only says what goes in each section.
 */
export function DemoPage(props: Partial<Record<SectionKey, ReactNode>>) {
  return (
    <>
      {SECTIONS.filter(({ key }) => props[key] !== undefined).map(({ key, title }) => (
        <section key={key} className="section" aria-labelledby={`section-${key}`}>
          <h2 className="section-title" id={`section-${key}`}>
            {title}
          </h2>
          <div className="specimens">{props[key]}</div>
        </section>
      ))}
    </>
  )
}

/** One specimen: the component on a stage, and the prop that made it. `wide` takes the whole row. */
export function Specimen({ label, wide, children }: { label: string; wide?: boolean; children: ReactNode }) {
  return (
    <figure className="specimen" data-wide={wide ? '' : undefined}>
      <div className="specimen-stage">{children}</div>
      <figcaption className="specimen-label">{label}</figcaption>
    </figure>
  )
}

// apps/docs/src/svelte/DemoPage.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { SECTIONS, type SectionKey } from '../site'

  /**
   * Every page, the same shape: the sections it has, in the one order, each a
   * grid of specimens. A page only says what goes in each section.
   */
  let props: Partial<Record<SectionKey, Snippet>> = $props()
</script>

{#each SECTIONS.filter(({ key }) => props[key] !== undefined) as { key, title } (key)}
  <section class="section" aria-labelledby="section-{key}">
    <h2 class="section-title" id="section-{key}">{title}</h2>
    <div class="specimens">{@render props[key]?.()}</div>
  </section>
{/each}
