// packages/svelte/src/components/link/Link.svelte
<script lang="ts">
  import { connect, type LinkProps, type LinkWords } from '@ggary/core/link'
  import { svelteNormalizer } from '@ggary/core'
  import type { Snippet } from 'svelte'

  let { external, words, children, ...rest }: LinkProps & { words?: LinkWords; children?: Snippet; [key: string]: unknown } = $props()
  const api = $derived(connect({ external }, svelteNormalizer, { words }))
</script>

<!-- One line: whitespace before the glyph would be drawn as a gap and underlined. -->
<a {...rest} {...api.rootProps}>{@render children?.()}{#if api.external}<span {...api.iconProps}></span><span {...api.hintProps}>{api.hintText}</span>{/if}</a>

// packages/react/src/components/link/Link.tsx
import type { AnchorHTMLAttributes, ReactNode } from 'react'
import { connect, type LinkProps as CoreLinkProps, type LinkWords } from '@ggary/core/link'
import { reactNormalizer } from '@ggary/core'

export interface LinkProps extends CoreLinkProps, AnchorHTMLAttributes<HTMLAnchorElement> {
  children?: ReactNode
  words?: LinkWords
}

export function Link({ external, words, children, ...rest }: LinkProps) {
  const api = connect({ external }, reactNormalizer, { words })
  return (
    <a {...rest} {...api.rootProps}>
      {children}
      {api.external && (
        <>
          <span {...api.iconProps} />
          <span {...api.hintProps}>{api.hintText}</span>
        </>
      )}
    </a>
  )
}
