// packages/svelte/src/components/metric/Metric.svelte
<script lang="ts">
  import { connect, type MetricProps } from '@ggary/core/metric'
  import { svelteNormalizer } from '@ggary/core'

  let props: MetricProps = $props()
  const api = $derived(connect(props, svelteNormalizer))
</script>

<div {...api.rootProps}>
  <div {...api.labelProps}>{props.label}</div>
  <div {...api.valueProps}>{api.valueText}{#if api.showUnit}<span {...api.unitProps}>{props.unit}</span>{/if}</div>
  {#if api.showDelta}
    <div {...api.deltaProps}>{#if api.showDeltaIcon}<span {...api.deltaIconProps}></span>{/if}{props.delta}</div>
  {/if}
</div>

// packages/react/src/components/metric/Metric.tsx
import type { ReactNode } from 'react'
import { connect, connectRow, type MetricProps, type MetricRowProps as CoreMetricRowProps } from '@ggary/core/metric'
import { reactNormalizer } from '@ggary/core'

export type { MetricProps }

export interface MetricRowProps extends CoreMetricRowProps {
  /** The metrics. */
  children?: ReactNode
}

export function Metric({ label, value, unit, delta, direction, tone, locale }: MetricProps) {
  const api = connect({ label, value, unit, delta, direction, tone, locale }, reactNormalizer)
  return (
    <div {...api.rootProps}>
      <div {...api.labelProps}>{label}</div>
      <div {...api.valueProps}>
        {api.valueText}
        {api.showUnit && <span {...api.unitProps}>{unit}</span>}
      </div>
      {api.showDelta && (
        <div {...api.deltaProps}>
          {api.showDeltaIcon && <span {...api.deltaIconProps} />}
          {delta}
        </div>
      )}
    </div>
  )
}

export function MetricRow({ joined, headline, children }: MetricRowProps) {
  const api = connectRow({ joined, headline }, reactNormalizer)
  return <div {...api.rootProps}>{children}</div>
}
