// packages/react/src/components/prose/Prose.tsx
import type { HTMLAttributes, ReactNode } from 'react'
import { connect, type ProseProps as CoreProseProps } from '@ggary/core/prose'
import { reactNormalizer } from '@ggary/core'

/** Children, or authored HTML through `dangerouslySetInnerHTML` — a markdown renderer's output. */
export interface ProseProps extends CoreProseProps, HTMLAttributes<HTMLDivElement> {
  children?: ReactNode
}

export function Prose({ size, children, ...rest }: ProseProps) {
  const api = connect({ size }, reactNormalizer)
  return (
    <div {...rest} {...api.rootProps}>
      {children}
    </div>
  )
}

// packages/svelte/src/components/prose/Prose.svelte
<script lang="ts">
  import { connect, type ProseProps } from '@ggary/core/prose'
  import { svelteNormalizer } from '@ggary/core'
  import type { Snippet } from 'svelte'

  /** Children, or authored HTML through `html` — a markdown renderer's output, trusted by whoever passes it. */
  let { size, html, children, ...rest }: ProseProps & { html?: string; children?: Snippet; [key: string]: unknown } = $props()
  const api = $derived(connect({ size }, svelteNormalizer))
</script>

<div {...rest} {...api.rootProps}>
  {#if html !== undefined}{@html html}{:else}{@render children?.()}{/if}
</div>
