// packages/react/src/components/search/Search.tsx
import { forwardRef, useRef, type InputHTMLAttributes } from 'react'
import { connect, type SearchProps as CoreSearchProps } from '@ggary/core/search'
import { mergeProps, reactNormalizer } from '@ggary/core'
import { useFieldControl } from '../field/Field'
import { useMergedRef } from '../../utils/use-merged-ref'
import { useFormReset } from '../../utils/use-form-reset'

export interface SearchProps
  extends CoreSearchProps,
    Omit<InputHTMLAttributes<HTMLInputElement>, keyof CoreSearchProps | 'type' | 'value' | 'defaultValue' | 'onChange' | 'size'> {
  /** Controlled. Omit and use `defaultValue` for uncontrolled. */
  value?: string
  defaultValue?: string
  onValueChange?: (value: string) => void
}

export const Search = forwardRef<HTMLInputElement, SearchProps>(function Search(props, forwardedRef) {
  const { size, name, placeholder, label, disabled, readOnly, required, invalid, value, defaultValue, onValueChange, ...rest } = props

  const api = connect(
    { size, name, placeholder, label, disabled, readOnly, required, invalid },
    reactNormalizer,
    { onValueChange, field: useFieldControl() ?? undefined }
  )

  const element = useRef<HTMLInputElement | null>(null)
  const ref = useMergedRef(element, forwardedRef)
  useFormReset(element)

  const valueProps = value !== undefined ? { value } : { defaultValue }
  return (
    <span {...api.rootProps}>
      <span {...api.iconProps} />
      <input ref={ref} {...mergeProps(rest, api.inputProps)} {...valueProps} />
    </span>
  )
})

// packages/svelte/src/components/search/Search.svelte
<script lang="ts">
  import { connect, type SearchProps } from '@ggary/core/search'
  import { mergeProps, onFormReset, svelteNormalizer } from '@ggary/core'
  import { getContext, untrack } from 'svelte'
  import { FIELD_CONTEXT, type FieldContext } from '../field/context'

  type Props = SearchProps & {
    /** Bindable: `bind:value`. A one-way `value` works too. */
    value?: string
    defaultValue?: string
    onValueChange?: (value: string) => void
    [key: string]: unknown
  }

  let {
    size, name, placeholder, label, disabled, readOnly, required, invalid,
    value = $bindable(), defaultValue, onValueChange, ...rest
  }: Props = $props()

  untrack(() => {
    if (value === undefined && defaultValue !== undefined) value = defaultValue
  })
  const initial = untrack(() => value)

  let element: HTMLInputElement
  $effect(() =>
    onFormReset(element, () => {
      value = initial
      element.value = initial ?? ''
    })
  )

  const field = getContext<FieldContext | undefined>(FIELD_CONTEXT)

  const api = $derived(
    connect({ size, name, placeholder, label, disabled, readOnly, required, invalid }, svelteNormalizer, {
      onValueChange,
      field: field?.control,
    })
  )

  const attrs = $derived(mergeProps(rest, api.inputProps))
</script>

<span {...api.rootProps}>
  <span {...api.iconProps}></span>
  <input bind:this={element} {...attrs} bind:value />
</span>
