// apps/docs/src/pages/popconfirm/Popconfirm.tsx
import { useEffect, useRef, type ReactNode } from 'react'
import { Button, Popconfirm } from '@ggary/react'
import { DemoPage, Specimen } from '../../react/DemoPage'
import { never, pressConfirm, refused } from './data'

/** Its question answered "yes" as the page loads. Once: StrictMode runs the effect twice. */
function Answered({ children }: { children: ReactNode }) {
  const host = useRef<HTMLDivElement>(null)
  const done = useRef(false)
  useEffect(() => {
    if (done.current || !host.current) return
    done.current = true
    pressConfirm(host.current)
  }, [])
  return (
    <div ref={host} className="frame">
      {children}
    </div>
  )
}

const lead = {
  title: 'Delete this lead?',
  description: 'Its history goes with it. This cannot be undone.',
  destructive: true,
  confirmLabel: 'Delete',
  trigger: (props: Record<string, unknown>) => (
    <Button {...props} destructive>
      Delete lead
    </Button>
  ),
}

export default function PopconfirmPage() {
  return (
    <DemoPage
      variants={
        <>
          <Specimen label="title, confirmLabel" wide>
            <div className="frame">
              <Popconfirm defaultOpen title="Publish the page now?" confirmLabel="Publish" trigger={(props) => <Button {...props}>Publish</Button>} />
            </div>
          </Specimen>
          <Specimen label="destructive, description" wide>
            <div className="frame">
              <Popconfirm defaultOpen {...lead} />
            </div>
          </Specimen>
        </>
      }
      states={
        <>
          <Specimen label="onConfirm: pending" wide>
            <Answered>
              <Popconfirm defaultOpen {...lead} onConfirm={never} />
            </Answered>
          </Specimen>
          <Specimen label="onConfirm: failed" wide>
            <Answered>
              <Popconfirm defaultOpen {...lead} onConfirm={refused} />
            </Answered>
          </Specimen>
        </>
      }
      composition={
        <Specimen label="trigger">
          <Popconfirm title="Publish the page now?" confirmLabel="Publish" trigger={(props) => <Button {...props}>Publish</Button>} />
        </Specimen>
      }
    />
  )
}

// apps/docs/src/pages/popconfirm/Popconfirm.svelte
<script lang="ts">
  import { Button, Popconfirm } from '@ggary/svelte'
  import DemoPage from '../../svelte/DemoPage.svelte'
  import Specimen from '../../svelte/Specimen.svelte'
  import { never, pressConfirm, refused } from './data'

  const lead = {
    title: 'Delete this lead?',
    description: 'Its history goes with it. This cannot be undone.',
    destructive: true,
    confirmLabel: 'Delete',
  }

  /** Its question answered "yes" as the page loads. */
  const answered = (host: HTMLElement) => pressConfirm(host)
</script>

{#snippet deleteLead(props: Record<string, unknown>)}<Button {...props} destructive>Delete lead</Button>{/snippet}
{#snippet publish(props: Record<string, unknown>)}<Button {...props}>Publish</Button>{/snippet}

<DemoPage>
  {#snippet variants()}
    <Specimen label="title, confirmLabel" wide>
      <div class="frame"><Popconfirm defaultOpen title="Publish the page now?" confirmLabel="Publish" trigger={publish} /></div>
    </Specimen>
    <Specimen label="destructive, description" wide>
      <div class="frame"><Popconfirm defaultOpen {...lead} trigger={deleteLead} /></div>
    </Specimen>
  {/snippet}
  {#snippet states()}
    <Specimen label="onConfirm: pending" wide>
      <div class="frame" {@attach answered}><Popconfirm defaultOpen {...lead} trigger={deleteLead} onConfirm={never} /></div>
    </Specimen>
    <Specimen label="onConfirm: failed" wide>
      <div class="frame" {@attach answered}><Popconfirm defaultOpen {...lead} trigger={deleteLead} onConfirm={refused} /></div>
    </Specimen>
  {/snippet}
  {#snippet composition()}
    <Specimen label="trigger">
      <Popconfirm title="Publish the page now?" confirmLabel="Publish" trigger={publish} />
    </Specimen>
  {/snippet}
</DemoPage>
