// packages/react/src/components/heatmap/Heatmap.tsx
import type { HTMLAttributes } from 'react'
import { connect, type HeatmapProps as CoreHeatmapProps, type HeatmapWords } from '@ggary/core/heatmap'
import { reactNormalizer } from '@ggary/core'

export interface HeatmapProps extends CoreHeatmapProps, Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
  /** The fixed text of the field's name and of a cell's title. */
  words?: HeatmapWords
}

export function Heatmap({ days, weekStart, label, unit, locale, words, ...rest }: HeatmapProps) {
  const api = connect({ days, weekStart, label, unit, locale }, reactNormalizer, words)
  return (
    <div {...rest} {...api.rootProps}>
      {api.weeks.map((week) => (
        <div key={week.key} {...week.weekProps}>
          {week.monthLabel && <span {...week.monthLabelProps}>{week.monthLabel}</span>}
          {week.days.map((day) => (
            <span key={day.key} {...day.dayProps} />
          ))}
        </div>
      ))}
    </div>
  )
}

// packages/svelte/src/components/heatmap/Heatmap.svelte
<script lang="ts">
  import { connect, type HeatmapProps, type HeatmapWords } from '@ggary/core/heatmap'
  import { svelteNormalizer } from '@ggary/core'

  type Props = HeatmapProps & {
    /** The fixed text of the field's name and of a cell's title. */
    words?: HeatmapWords
    [key: string]: unknown
  }

  let { days, weekStart, label, unit, locale, words, ...rest }: Props = $props()
  const api = $derived(connect({ days, weekStart, label, unit, locale }, svelteNormalizer, words))
</script>

<div {...rest} {...api.rootProps}>
  {#each api.weeks as week (week.key)}
    <div {...week.weekProps}>
      {#if week.monthLabel}<span {...week.monthLabelProps}>{week.monthLabel}</span>{/if}
      {#each week.days as day (day.key)}<span {...day.dayProps}></span>{/each}
    </div>
  {/each}
</div>
