// packages/react/src/components/combobox/Combobox.tsx
import { useEffect, useId, useLayoutEffect, useRef, useState, useSyncExternalStore } from 'react'
import {
  attachComboboxSource,
  connect,
  createComboboxMachine,
  type ComboboxItem,
  type ComboboxLoad,
  type ComboboxWords,
} from '@ggary/core/combobox'
import { attachPopover, mergeProps, reactNormalizer, scrollIntoViewIfNeeded } from '@ggary/core'
import type { ControlSize } from '@ggary/core'
import { useFormReset } from '../../utils/use-form-reset'
import { useFormField } from '../form/Form'

export interface ComboboxProps {
  /** `sm`, `md` or `lg`, as Input's and Button's. Default `md`. */
  size?: ControlSize
  label?: string
  /** The options, filtered in the page as the person types. */
  items?: ComboboxItem[]
  /** Or a server that answers a query. Takes precedence over `items`. */
  load?: ComboboxLoad
  /** How long the typing pauses before `load` is asked, in ms. Default 200. */
  debounce?: number
  /** Fewer characters ask nothing. Default 0: an empty field shows suggestions. */
  minLength?: number
  /** Several values, as chips in the field. */
  multiple?: boolean
  /** Controlled. A single combobox takes a string; omit and use `defaultValue` for uncontrolled. */
  value?: string | string[] | null
  defaultValue?: string | string[] | null
  /** The chosen items' labels, when `load` knows them and `items` does not. */
  selectedItems?: ComboboxItem[]
  onValueChange?: (value: string[], items: ComboboxItem[]) => void
  /**
   * Typed text that matches no option can be created: "Create …" ends the
   * list. Return the new option (or a promise of it) and it is chosen; add it
   * to `items` to keep it. A rejection says why.
   */
  onCreate?: (text: string) => ComboboxItem | void | Promise<ComboboxItem | void>
  placeholder?: string
  disabled?: boolean
  /** How many options are drawn at once. Default 50. */
  limit?: number
  name?: string
  words?: ComboboxWords
}

/** A text field with a list of options: type to narrow it, arrows and Enter to choose. */
export function Combobox(props: ComboboxProps) {
  const {
    size,
    label, items, load, debounce, minLength, multiple = false, value, defaultValue, selectedItems, onValueChange, onCreate,
    placeholder, disabled = false, limit, name, words,
  } = props
  const id = `gg-combobox-${useId().replace(/:/g, '')}`
  const callbacks = useRef<{ onValueChange?: typeof onValueChange; load?: typeof load; onCreate?: typeof onCreate; edited?: () => void }>({ onValueChange, load, onCreate })
  Object.assign(callbacks.current, { onValueChange, load, onCreate })

  const [machine] = useState(() =>
    createComboboxMachine({
      id,
      items: load ? undefined : items,
      value,
      defaultValue,
      selectedItems,
      multiple,
      disabled,
      limit,
      creatable: onCreate !== undefined,
      onValueChange: (next, chosen) => {
        callbacks.current.onValueChange?.(next, chosen)
        callbacks.current.edited?.()
      },
      onCreate: (text) => callbacks.current.onCreate?.(text),
    })
  )
  const state = useSyncExternalStore(machine.subscribe, machine.getState, machine.getState)
  const api = connect(state, machine.send, reactNormalizer, { ...words, placeholder: placeholder ?? words?.placeholder, name, size })
  // Inside a Form, by name: the error its rules hold for this choice.
  const form = useFormField(name, api.ids.input, label)
  callbacks.current.edited = () => form.edited(document.getElementById(api.ids.input))

  useEffect(() => {
    if (!load && items) machine.send({ type: 'SYNC_SOURCE', items })
  }, [machine, items, load])
  const creatable = onCreate !== undefined
  useEffect(() => machine.send({ type: 'SYNC_OPTIONS', multiple, disabled, limit, creatable }), [machine, multiple, disabled, limit, creatable])
  useEffect(() => {
    if (value !== undefined) machine.send({ type: 'SYNC_VALUE', value, items: selectedItems })
  }, [machine, value, selectedItems])
  const hasLoad = Boolean(load)
  useEffect(() => {
    if (!hasLoad) return
    return attachComboboxSource(machine, (query, signal) => callbacks.current.load!(query, signal), { debounce, minLength })
  }, [machine, hasLoad, debounce, minLength])

  const inputRef = useRef<HTMLInputElement>(null)
  const controlRef = useRef<HTMLDivElement>(null)
  const positionerRef = useRef<HTMLDivElement>(null)
  const contentRef = useRef<HTMLUListElement>(null)
  useFormReset(inputRef, () => {
    if (value === undefined) machine.send({ type: 'SYNC_VALUE', value: defaultValue ?? null })
  })

  useLayoutEffect(() => {
    if (!state.open || !controlRef.current || !positionerRef.current) return
    // The focus stays in the field: no focus management, only placement and dismissal.
    const popover = attachPopover(controlRef.current, positionerRef.current, {
      sameWidth: true,
      gutter: 4,
      onDismiss: () => machine.send({ type: 'CLOSE' }),
    })
    return () => popover.destroy()
  }, [machine, state.open])

  useEffect(() => {
    if (!state.open || state.highlightedIndex < 0) return
    scrollIntoViewIfNeeded(document.getElementById(api.ids.item(state.highlightedIndex)), contentRef.current)
  }, [api.ids, state.open, state.highlightedIndex])

  return (
    <div {...api.rootProps}>
      {label && <label {...api.labelProps}>{label}</label>}
      <div ref={controlRef} {...api.controlProps}>
        {multiple &&
          api.selectedItems.map((item) => {
            const chip = api.getChipProps(item)
            return (
              <span key={item.value} {...chip.chipProps}>
                <span {...chip.chipTextProps}>{item.label}</span>
                <button {...chip.removeProps}>
                  <span {...chip.removeIconProps} />
                </button>
              </span>
            )
          })}
        <input ref={inputRef} {...mergeProps(api.inputProps, form.field.controlProps)} />
        <button {...api.clearProps}>
          <span {...api.clearIconProps} />
        </button>
        <button {...api.triggerProps}>
          <span {...api.triggerIconProps} />
        </button>
      </div>
      <span {...form.field.errorProps}>{form.error}</span>
      <div ref={positionerRef} {...api.positionerProps}>
        <ul ref={contentRef} {...api.contentProps}>
          {api.items.length === 0 && <li {...api.emptyProps}>{api.emptyText}</li>}
          {api.items.map((item, index) => (
            <li key={item.value} {...api.getItemProps(item, index)}>
              <span {...api.itemTextProps}>{api.labelOf(item)}</span>
              {item.description && <span {...api.itemDescriptionProps}>{item.description}</span>}
              <span {...api.itemIndicatorProps} />
            </li>
          ))}
          {api.moreText && <li {...api.moreProps}>{api.moreText}</li>}
        </ul>
      </div>
      <span {...api.statusProps}>{api.statusText}</span>
      {name && api.value.map((entry) => <input key={entry} {...api.getHiddenInputProps(entry)} />)}
    </div>
  )
}

// packages/svelte/src/components/combobox/Combobox.svelte
<script lang="ts">
  import type { ControlSize } from '@ggary/core'
  import {
    attachComboboxSource,
    connect,
    createComboboxMachine,
    type ComboboxItem,
    type ComboboxLoad,
    type ComboboxWords,
  } from '@ggary/core/combobox'
  import { attachPopover, mergeProps, onFormReset, scrollIntoViewIfNeeded, svelteNormalizer, uid } from '@ggary/core'
  import { useFormField } from '../form/context.svelte'
  import { untrack } from 'svelte'

  type Props = {
    /** `sm`, `md` or `lg`, as Input's and Button's. Default `md`. */
    size?: ControlSize
    label?: string
    /** The options, filtered in the page as the person types. */
    items?: ComboboxItem[]
    /** Or a server that answers a query. Takes precedence over `items`. */
    load?: ComboboxLoad
    debounce?: number
    minLength?: number
    multiple?: boolean
    /** Bindable: `bind:value`. A single combobox holds a string, a multiple one a list. */
    value?: string | string[] | null
    defaultValue?: string | string[] | null
    selectedItems?: ComboboxItem[]
    onValueChange?: (value: string[], items: ComboboxItem[]) => void
    /** Typed text that matches no option can be created: "Create …" ends the list. Return the new option and it is chosen. */
    onCreate?: (text: string) => ComboboxItem | void | Promise<ComboboxItem | void>
    placeholder?: string
    disabled?: boolean
    limit?: number
    name?: string
    words?: ComboboxWords
  }

  let {
    size,
    label, items, load, debounce, minLength, multiple = false, value = $bindable(), defaultValue, selectedItems, onValueChange, onCreate,
    placeholder, disabled = false, limit, name, words,
  }: Props = $props()

  const initial = untrack(() => (value !== undefined ? value : (defaultValue ?? null)))
  // Uncontrolled at heart, as `bind:value` is: a choice moves it and writes the binding.
  const machine = untrack(() =>
    createComboboxMachine({
      id: uid('gg-combobox'),
      items: load ? undefined : items,
      defaultValue: initial,
      selectedItems,
      multiple,
      disabled,
      limit,
      creatable: onCreate !== undefined,
      onCreate: (text) => onCreate?.(text),
      onValueChange: (next, chosen) => {
        value = multiple ? next : (next[0] ?? null)
        onValueChange?.(next, chosen)
        form.edited()
      },
    })
  )

  let snapshot = $state.raw(machine.getState())
  $effect(() => machine.subscribe((next) => (snapshot = next)))
  // Effects that attach on open read this, not the snapshot: a new snapshot on every
  // change would detach and attach them again on each key.
  const isOpen = $derived(snapshot.open)
  const api = $derived(connect(snapshot, machine.send, svelteNormalizer, { ...words, placeholder: placeholder ?? words?.placeholder, name, size }))
  // Inside a Form, by name: the error its rules hold for this choice.
  const form = useFormField(() => name, () => api.ids.input, () => label)

  $effect(() => {
    if (!load && items) machine.send({ type: 'SYNC_SOURCE', items })
  })
  $effect(() => machine.send({ type: 'SYNC_OPTIONS', multiple, disabled, limit, creatable: onCreate !== undefined }))
  $effect(() => {
    if (value !== undefined) machine.send({ type: 'SYNC_VALUE', value, items: untrack(() => selectedItems) })
  })
  const hasLoad = $derived(Boolean(load))
  $effect(() => {
    if (!hasLoad) return
    const options = { debounce, minLength }
    return untrack(() => attachComboboxSource(machine, (query, signal) => load!(query, signal), options))
  })

  let inputEl = $state<HTMLInputElement | null>(null)
  let controlEl = $state<HTMLDivElement | null>(null)
  let positionerEl = $state<HTMLDivElement | null>(null)
  let contentEl = $state<HTMLUListElement | null>(null)

  $effect(() =>
    onFormReset(inputEl, () => {
      value = initial
      machine.send({ type: 'SYNC_VALUE', value: initial })
    })
  )

  $effect(() => {
    if (!isOpen || !controlEl || !positionerEl) return
    const popover = attachPopover(controlEl, positionerEl, { sameWidth: true, gutter: 4, onDismiss: () => machine.send({ type: 'CLOSE' }) })
    return () => popover.destroy()
  })

  $effect(() => {
    if (!isOpen || snapshot.highlightedIndex < 0) return
    scrollIntoViewIfNeeded(document.getElementById(api.ids.item(snapshot.highlightedIndex)), contentEl)
  })
</script>

<div {...api.rootProps}>
  {#if label}<label {...api.labelProps}>{label}</label>{/if}
  <div bind:this={controlEl} {...api.controlProps}>
    {#if multiple}
      {#each api.selectedItems as item (item.value)}
        {@const chip = api.getChipProps(item)}
        <span {...chip.chipProps}>
          <span {...chip.chipTextProps}>{item.label}</span>
          <button {...chip.removeProps}><span {...chip.removeIconProps}></span></button>
        </span>
      {/each}
    {/if}
    <input bind:this={inputEl} {...mergeProps(api.inputProps, form.field.controlProps)} />
    <button {...api.clearProps}><span {...api.clearIconProps}></span></button>
    <button {...api.triggerProps}><span {...api.triggerIconProps}></span></button>
  </div>
  <span {...form.field.errorProps}>{form.error}</span>
  <div bind:this={positionerEl} {...api.positionerProps}>
    <ul bind:this={contentEl} {...api.contentProps}>
      {#if api.items.length === 0}<li {...api.emptyProps}>{api.emptyText}</li>{/if}
      {#each api.items as item, index (item.value)}
        <li {...api.getItemProps(item, index)}>
          <span {...api.itemTextProps}>{api.labelOf(item)}</span>
          {#if item.description}<span {...api.itemDescriptionProps}>{item.description}</span>{/if}
          <span {...api.itemIndicatorProps}></span>
        </li>
      {/each}
      {#if api.moreText}<li {...api.moreProps}>{api.moreText}</li>{/if}
    </ul>
  </div>
  <span {...api.statusProps}>{api.statusText}</span>
  {#if name}
    {#each api.value as entry (entry)}<input {...api.getHiddenInputProps(entry)} />{/each}
  {/if}
</div>
