// packages/svelte/src/components/panel/Panel.svelte
<script lang="ts">
  import { connect, type PanelProps } from '@ggary/core/panel'
  import { svelteNormalizer, uid } from '@ggary/core'
  import type { Snippet } from 'svelte'

  type Props = PanelProps & {
    /** Controls in the header, at its far edge. */
    actions?: Snippet
    /** A strip of tools between the header and the body; see Toolbar. */
    toolbar?: Snippet
    children?: Snippet
    [key: string]: unknown
  }

  let { title, headingLevel, body, plain, rank, tone, region, scrollable, actions, toolbar, children, ...rest }: Props = $props()
  const id = uid('gg-panel')
  const api = $derived(connect({ id, title, headingLevel, body, plain, rank, tone, region, scrollable }, svelteNormalizer))
</script>

<div {...api.rootProps} {...rest}>
  {#if title !== undefined || actions}
    <div {...api.headerProps}>
      {#if title !== undefined}
        <svelte:element this={api.titleElement} {...api.titleProps}>{title}</svelte:element>
      {/if}
      {#if actions}
        <div {...api.actionsProps}>{@render actions()}</div>
      {/if}
    </div>
  {/if}
  {@render toolbar?.()}
  <div {...api.bodyProps}>{@render children?.()}</div>
</div>

// packages/react/src/components/panel/Panel.tsx
import { useId, type HTMLAttributes, type ReactNode } from 'react'
import { connect, type PanelProps as CorePanelProps } from '@ggary/core/panel'
import { reactNormalizer } from '@ggary/core'

export interface PanelProps extends CorePanelProps, Omit<HTMLAttributes<HTMLDivElement>, 'title'> {
  /** Controls in the header, at its far edge. */
  actions?: ReactNode
  /** A strip of tools between the header and the body; see Toolbar. */
  toolbar?: ReactNode
  children?: ReactNode
}

export function Panel({ title, headingLevel, body, plain, rank, tone, region, scrollable, actions, toolbar, children, ...rest }: PanelProps) {
  const id = `gg-panel-${useId().replace(/:/g, '')}`
  const api = connect({ id, title, headingLevel, body, plain, rank, tone, region, scrollable }, reactNormalizer)
  const Title = api.titleElement
  return (
    <div {...api.rootProps} {...rest}>
      {(title !== undefined || actions !== undefined) && (
        <div {...api.headerProps}>
          {title !== undefined && <Title {...api.titleProps}>{title}</Title>}
          {actions !== undefined && <div {...api.actionsProps}>{actions}</div>}
        </div>
      )}
      {toolbar}
      <div {...api.bodyProps}>{children}</div>
    </div>
  )
}
