// packages/svelte/src/components/toolbar/Toolbar.svelte
<script lang="ts">
  import { connect, type ToolbarProps } from '@ggary/core/toolbar'
  import { attachToolbarKeys, svelteNormalizer } from '@ggary/core'
  import type { Snippet } from 'svelte'

  let {
    label, orientation = 'horizontal', children, ...rest
  }: ToolbarProps & { children: Snippet; [key: string]: unknown } = $props()

  const api = $derived(connect({ label, orientation }, svelteNormalizer))
</script>

<div
  {...rest}
  {...api.rootProps}
  {@attach (root) => (api.managed ? attachToolbarKeys(root, orientation) : undefined)}
>
  {@render children()}
</div>

// packages/react/src/components/toolbar/Toolbar.tsx
import { useEffect, useRef, type HTMLAttributes, type ReactNode } from 'react'
import { connect, type ToolbarProps as CoreToolbarProps } from '@ggary/core/toolbar'
import { attachToolbarKeys, reactNormalizer } from '@ggary/core'

export interface ToolbarProps extends CoreToolbarProps, HTMLAttributes<HTMLDivElement> {
  children: ReactNode
}

export function Toolbar({ label, orientation = 'horizontal', children, ...rest }: ToolbarProps) {
  const api = connect({ label, orientation }, reactNormalizer)
  const root = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!api.managed || !root.current) return
    return attachToolbarKeys(root.current, orientation)
  }, [api.managed, orientation])

  return (
    <div ref={root} {...rest} {...api.rootProps}>
      {children}
    </div>
  )
}

/** A line between meaningful groups of tools. */
export function ToolbarSeparator() {
  const api = connect({}, reactNormalizer)
  return <span {...api.separatorProps} />
}

/** One per strip: everything after it goes to the far edge. */
export function ToolbarSpacer() {
  const api = connect({}, reactNormalizer)
  return <span {...api.spacerProps} />
}
