// packages/react/src/components/log/Log.tsx
import { useEffect, useRef, type HTMLAttributes } from 'react'
import { attachLogTail, connect, type LogProps as CoreLogProps, type LogWords } from '@ggary/core/log'
import { reactNormalizer } from '@ggary/core'

export interface LogProps extends CoreLogProps, Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
  /** The levels in words, where the machine's word is not the reader's. */
  words?: LogWords
  /**
   * Hold the bottom as lines arrive, and let go the moment the reader scrolls
   * up. Default true — a log nobody scrolls should show its newest line.
   */
  tail?: boolean
}

export function Log({ lines, label, locale, timeZone, announce, words, tail = true, ...rest }: LogProps) {
  const api = connect({ lines, label, locale, timeZone, announce }, reactNormalizer, { words })
  const root = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!tail || !root.current) return
    const following = attachLogTail(root.current)
    return () => following.dispose()
  }, [tail])

  return (
    <div ref={root} {...rest} {...api.rootProps}>
      {api.lines.map((line) => (
        <div key={line.key} {...line.lineProps}>
          <span {...api.timeProps}>{line.time}</span>
          <span {...api.levelProps}>{line.level}</span>
          <span {...api.messageProps}>{line.text}</span>
        </div>
      ))}
    </div>
  )
}

// packages/svelte/src/components/log/Log.svelte
<script lang="ts">
  import { attachLogTail, connect, type LogProps, type LogWords } from '@ggary/core/log'
  import { svelteNormalizer } from '@ggary/core'

  type Props = LogProps & {
    /** The levels in words, where the machine's word is not the reader's. */
    words?: LogWords
    /**
     * Hold the bottom as lines arrive, and let go the moment the reader
     * scrolls up. Default true — a log nobody scrolls should show its newest line.
     */
    tail?: boolean
    [key: string]: unknown
  }

  let { lines, label, locale, timeZone, announce, words, tail = true, ...rest }: Props = $props()
  const api = $derived(connect({ lines, label, locale, timeZone, announce }, svelteNormalizer, words))

  let root = $state<HTMLDivElement | null>(null)
  $effect(() => {
    if (!tail || !root) return
    const following = attachLogTail(root)
    return () => following.dispose()
  })
</script>

<div bind:this={root} {...rest} {...api.rootProps}>
  {#each api.lines as line (line.key)}
    <div {...line.lineProps}>
      <span {...api.timeProps}>{line.time}</span>
      <span {...api.levelProps}>{line.level}</span>
      <span {...api.messageProps}>{line.text}</span>
    </div>
  {/each}
</div>
