// packages/react/src/components/card/Card.tsx
import type { HTMLAttributes, ReactNode } from 'react'
import { connect, type CardProps as CoreCardProps } from '@ggary/core/card'
import { reactNormalizer } from '@ggary/core'

export interface CardProps extends CoreCardProps, Omit<HTMLAttributes<HTMLElement>, 'title'> {
  children?: ReactNode
}

export function Card({ title, subtitle, headingLevel, href, interactive, plain, rank, tone, children, ...rest }: CardProps) {
  const api = connect({ title, subtitle, headingLevel, href, interactive, plain, rank, tone }, reactNormalizer)
  const Root = api.element
  const Title = api.titleElement
  return (
    <Root {...api.rootProps} {...rest}>
      {api.showHeader && (
        <div {...api.headerProps}>
          {title !== undefined && <Title {...api.titleProps}>{title}</Title>}
          {subtitle !== undefined && <p {...api.subtitleProps}>{subtitle}</p>}
        </div>
      )}
      {children}
    </Root>
  )
}

// packages/svelte/src/components/card/Card.svelte
<script lang="ts">
  import { connect, type CardProps } from '@ggary/core/card'
  import { svelteNormalizer } from '@ggary/core'
  import type { Snippet } from 'svelte'

  type Props = CardProps & { children?: Snippet; [key: string]: unknown }

  let { title, subtitle, headingLevel, href, interactive, plain, rank, tone, children, ...rest }: Props = $props()
  const api = $derived(connect({ title, subtitle, headingLevel, href, interactive, plain, rank, tone }, svelteNormalizer))
</script>

<svelte:element this={api.element} {...api.rootProps} {...rest}>
  {#if api.showHeader}
    <div {...api.headerProps}>
      {#if title !== undefined}
        <svelte:element this={api.titleElement} {...api.titleProps}>{title}</svelte:element>
      {/if}
      {#if subtitle !== undefined}
        <p {...api.subtitleProps}>{subtitle}</p>
      {/if}
    </div>
  {/if}
  {@render children?.()}
</svelte:element>
