// packages/react/src/components/legend/Legend.tsx
import type { HTMLAttributes } from 'react'
import { connect, type LegendProps as CoreLegendProps, type LegendWords } from '@ggary/core/legend'
import { reactNormalizer } from '@ggary/core'

export interface LegendProps extends CoreLegendProps, Omit<HTMLAttributes<HTMLUListElement>, 'children'> {
  /** The default name of the list in another language. */
  words?: Partial<LegendWords>
}

/** The key to a chart's colours: a swatch, the series in words, and its quantity. */
export function Legend({ items, direction, label, words, ...rest }: LegendProps) {
  const api = connect({ items, direction, label }, reactNormalizer, { words })
  return (
    <ul {...api.rootProps} {...rest}>
      {api.items.map((item, index) => {
        const entry = api.getItemProps(item)
        return (
          // Two series may share a label, so the position keys the item.
          <li key={index} {...entry.itemProps}>
            <span {...entry.swatchProps} />
            <span {...entry.labelProps}>{item.label}</span>
            {entry.showValue && <span {...entry.valueProps}>{item.value}</span>}
          </li>
        )
      })}
    </ul>
  )
}

// packages/svelte/src/components/legend/Legend.svelte
<script lang="ts">
  import { connect, type LegendProps, type LegendWords } from '@ggary/core/legend'
  import { svelteNormalizer } from '@ggary/core'

  /* words: the default name of the list in another language. */
  type Props = LegendProps & {
    words?: Partial<LegendWords>
    [key: string]: unknown
  }

  let { items, direction, label, words, ...rest }: Props = $props()
  const api = $derived(connect({ items, direction, label }, svelteNormalizer, words))
</script>

<ul {...api.rootProps} {...rest}>
  <!-- Two series may share a label, so the position keys the item. -->
  {#each api.items as item, index (index)}
    {@const entry = api.getItemProps(item)}
    <li {...entry.itemProps}>
      <span {...entry.swatchProps}></span>
      <span {...entry.labelProps}>{item.label}</span>
      {#if entry.showValue}<span {...entry.valueProps}>{item.value}</span>{/if}
    </li>
  {/each}
</ul>
