// packages/svelte/src/components/input-group/InputGroup.svelte
<script lang="ts">
  import { connect, type InputGroupProps } from '@ggary/core/input-group'
  import { svelteNormalizer } from '@ggary/core'
  import type { Snippet } from 'svelte'

  let { prefix, suffix, size, disabled, invalid, children }: InputGroupProps & { children: Snippet } = $props()

  const api = $derived(connect({ prefix, suffix, size, disabled, invalid }, svelteNormalizer))
</script>

<div {...api.rootProps}>
  {#if api.showPrefix}
    <span {...api.prefixProps}>{api.prefix}</span>
  {/if}
  {@render children()}
  {#if api.showSuffix}
    <span {...api.suffixProps}>{api.suffix}</span>
  {/if}
</div>

// packages/react/src/components/input-group/InputGroup.tsx
import type { HTMLAttributes, ReactNode } from 'react'
import { connect, type InputGroupProps as CoreInputGroupProps } from '@ggary/core/input-group'
import { reactNormalizer } from '@ggary/core'

export interface InputGroupProps extends CoreInputGroupProps, Omit<HTMLAttributes<HTMLDivElement>, 'prefix'> {
  children: ReactNode
}

export function InputGroup({ prefix, suffix, size, disabled, invalid, children, ...rest }: InputGroupProps) {
  const api = connect({ prefix, suffix, size, disabled, invalid }, reactNormalizer)
  return (
    <div {...rest} {...api.rootProps}>
      {api.showPrefix && <span {...api.prefixProps}>{api.prefix}</span>}
      {children}
      {api.showSuffix && <span {...api.suffixProps}>{api.suffix}</span>}
    </div>
  )
}
