// packages/react/src/components/layout/Shell.tsx
import { useEffect, useId, useRef, useState, useSyncExternalStore, type HTMLAttributes, type ReactNode } from 'react'
import {
  connect,
  createShellMachine,
  type ShellChangeDetails,
  type ShellCollapse,
  type ShellConnectOptions,
} from '@ggary/core/shell'
import { attachShellDrawer, reactNormalizer } from '@ggary/core'

export interface ShellProps extends ShellConnectOptions, Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
  /** The application's name at the top of the side column — a link home, usually. */
  brand?: ReactNode
  /** The side column: a Nav, a Rail. Without it the shell has no column and no drawer. */
  aside?: ReactNode
  /** The strip over the work area: breadcrumbs, a search, the account. */
  header?: ReactNode
  /** The status strip along the bottom. */
  footer?: ReactNode
  /** The work area: the page's `main`. */
  children: ReactNode
  /** What the column becomes on a narrow screen. Default `drawer`. */
  collapse?: ShellCollapse
  /** The drawer. Controlled; omit for uncontrolled. */
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean, details: ShellChangeDetails) => void
}

export function Shell(props: ShellProps) {
  const {
    brand, aside, header, footer, children, collapse, open, defaultOpen, onOpenChange,
    skipLabel, toggleLabel, asideLabel, ...rest
  } = props
  const id = `gg-shell-${useId().replace(/:/g, '')}`
  const callbacks = useRef({ onOpenChange })
  callbacks.current = { onOpenChange }

  const [machine] = useState(() =>
    createShellMachine({ id, open, defaultOpen, collapse, onOpenChange: (next, details) => callbacks.current.onOpenChange?.(next, details) })
  )
  const state = useSyncExternalStore(machine.subscribe, machine.getState, machine.getState)
  const api = connect(state, machine.send, reactNormalizer, { skipLabel, toggleLabel, asideLabel })

  useEffect(() => {
    if (open !== undefined) machine.send({ type: 'SYNC_OPEN', open })
  }, [machine, open])
  useEffect(() => machine.send({ type: 'SYNC_OPTIONS', collapse }), [machine, collapse])

  const rootRef = useRef<HTMLDivElement>(null)
  const asideRef = useRef<HTMLDivElement>(null)
  const toggleRef = useRef<HTMLButtonElement>(null)
  useEffect(() => {
    if (!api.open || !rootRef.current || !asideRef.current) return
    return attachShellDrawer(rootRef.current, asideRef.current, toggleRef.current, {
      onDismiss: (reason) => machine.send({ type: 'CLOSE', reason }),
    })
  }, [api.open, machine])

  const column = brand != null || aside != null
  return (
    <div ref={rootRef} {...rest} {...api.rootProps}>
      <a {...api.skipLinkProps}>{api.skipLabel}</a>
      {column && (
        <div ref={asideRef} {...api.asideProps}>
          {brand != null && <div {...api.brandProps}>{brand}</div>}
          {aside}
        </div>
      )}
      <header {...api.headerProps}>
        {column && (
          <button ref={toggleRef} {...api.toggleProps}>
            <span {...api.toggleIconProps} />
          </button>
        )}
        {header}
      </header>
      <main {...api.mainProps}>{children}</main>
      {footer != null && <footer {...api.footerProps}>{footer}</footer>}
    </div>
  )
}

// packages/svelte/src/components/layout/Shell.svelte
<script lang="ts">
  import { connect, createShellMachine, type ShellChangeDetails, type ShellCollapse } from '@ggary/core/shell'
  import { attachShellDrawer, svelteNormalizer, uid } from '@ggary/core'
  import { untrack, type Snippet } from 'svelte'

  type Props = {
    /** The application's name at the top of the side column. */
    brand?: Snippet
    /** The side column: a Nav, a Rail. Without it the shell has no column and no drawer. */
    aside?: Snippet
    /** The strip over the work area. */
    header?: Snippet
    /** The status strip along the bottom. */
    footer?: Snippet
    /** The work area: the page's `main`. */
    children: Snippet
    /** What the column becomes on a narrow screen. Default `drawer`. */
    collapse?: ShellCollapse
    /** Bindable: `bind:open`, the drawer. */
    open?: boolean
    defaultOpen?: boolean
    onOpenChange?: (open: boolean, details: ShellChangeDetails) => void
    skipLabel?: string
    toggleLabel?: string
    asideLabel?: string
    style?: string
  }

  let {
    brand, aside, header, footer, children, collapse, open = $bindable(), defaultOpen, onOpenChange,
    skipLabel, toggleLabel, asideLabel, style,
  }: Props = $props()

  const machine = untrack(() =>
    createShellMachine({
      id: uid('gg-shell'),
      defaultOpen: open ?? defaultOpen,
      collapse,
      onOpenChange: (next, details) => {
        open = next
        onOpenChange?.(next, details)
      },
    })
  )

  let snapshot = $state(machine.getState())
  $effect(() => machine.subscribe((next) => (snapshot = next)))
  const api = $derived(connect(snapshot, machine.send, svelteNormalizer, { skipLabel, toggleLabel, asideLabel }))

  $effect(() => {
    if (open !== undefined) machine.send({ type: 'SYNC_OPEN', open })
  })
  $effect(() => machine.send({ type: 'SYNC_OPTIONS', collapse }))

  let root: HTMLDivElement
  let column = $state<HTMLDivElement>()
  let toggle = $state<HTMLButtonElement>()
  $effect(() => {
    if (!api.open || !column) return
    const aside = column
    return untrack(() => attachShellDrawer(root, aside, toggle ?? null, { onDismiss: (reason) => machine.send({ type: 'CLOSE', reason }) }))
  })

  const hasColumn = $derived(Boolean(brand || aside))
</script>

<div bind:this={root} {...api.rootProps} {style}>
  <a {...api.skipLinkProps}>{api.skipLabel}</a>
  {#if hasColumn}
    <div bind:this={column} {...api.asideProps}>
      {#if brand}<div {...api.brandProps}>{@render brand()}</div>{/if}
      {@render aside?.()}
    </div>
  {/if}
  <header {...api.headerProps}>
    {#if hasColumn}
      <button bind:this={toggle} {...api.toggleProps}><span {...api.toggleIconProps}></span></button>
    {/if}
    {@render header?.()}
  </header>
  <main {...api.mainProps}>{@render children()}</main>
  {#if footer}<footer {...api.footerProps}>{@render footer()}</footer>{/if}
</div>
