// packages/react/src/components/layout/Split.tsx
import { useEffect, useId, useRef, useState, useSyncExternalStore, type CSSProperties, type HTMLAttributes, type ReactNode } from 'react'
import { connect, createSplitMachine, type SplitOptions } from '@ggary/core/split'
import { reactNormalizer } from '@ggary/core'

export interface SplitProps extends Partial<SplitOptions>, Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
  /** The separator's name, required: "Resize the lead list". */
  label: string
  /** The two panes, in reading order. */
  children: [ReactNode, ReactNode]
  /** The primary pane's starting size in px — a stored one. Defaults to `defaultSize`. */
  size?: number
  collapsed?: boolean
  /** The least the other pane keeps, in px. Default 200. */
  restMin?: number
  /** Every change of size or fold, to keep the layout. */
  onSizeChange?: (size: number, details: { collapsed: boolean }) => void
}

/** Two panes and a separator that can be dragged, or moved from the keyboard. */
export function Split(props: SplitProps) {
  const {
    label, children, size, collapsed, restMin, onSizeChange, style,
    orientation, primary, min, max, step, collapsible, defaultSize, ...rest
  } = props
  const id = `gg-split-${useId().replace(/:/g, '')}`
  const callbacks = useRef({ onSizeChange })
  callbacks.current = { onSizeChange }

  const [machine] = useState(() =>
    createSplitMachine({
      id, size, collapsed, orientation, primary, min, max, step, collapsible, defaultSize,
      onSizeChange: (next, details) => callbacks.current.onSizeChange?.(next, details),
    })
  )
  const state = useSyncExternalStore(machine.subscribe, machine.getState, machine.getState)
  const api = connect(state, machine.send, reactNormalizer, { label, restMin })

  useEffect(
    () => machine.send({ type: 'SYNC_OPTIONS', orientation, primary, min, max, step, collapsible, defaultSize }),
    [machine, orientation, primary, min, max, step, collapsible, defaultSize]
  )

  const [first, second] = children
  return (
    <div {...rest} {...api.rootProps} style={{ ...(api.rootProps.style as CSSProperties | undefined), ...style }}>
      <div {...api.startPaneProps}>{first}</div>
      <div {...api.separatorProps}>
        <span {...api.handleProps} />
      </div>
      <div {...api.endPaneProps}>{second}</div>
    </div>
  )
}

// packages/svelte/src/components/layout/Split.svelte
<script lang="ts">
  import { connect, createSplitMachine, type SplitOrientation, type SplitPrimary } from '@ggary/core/split'
  import { svelteNormalizer, uid } from '@ggary/core'
  import { untrack, type Snippet } from 'svelte'

  type Props = {
    /** The separator's name, required: "Resize the lead list". */
    label: string
    /** The first pane, in reading order. */
    first: Snippet
    second: Snippet
    orientation?: SplitOrientation
    primary?: SplitPrimary
    min?: number
    max?: number
    step?: number
    collapsible?: boolean
    defaultSize?: number
    /** The primary pane's starting size in px — a stored one. */
    size?: number
    collapsed?: boolean
    /** The least the other pane keeps, in px. Default 200. */
    restMin?: number
    onSizeChange?: (size: number, details: { collapsed: boolean }) => void
    style?: string
  }

  let {
    label, first, second, orientation, primary, min, max, step, collapsible, defaultSize, size, collapsed, restMin,
    onSizeChange, style,
  }: Props = $props()

  const machine = untrack(() =>
    createSplitMachine({
      id: uid('gg-split'), size, collapsed, orientation, primary, min, max, step, collapsible, defaultSize,
      onSizeChange: (next, details) => onSizeChange?.(next, details),
    })
  )
  let snapshot = $state(machine.getState())
  $effect(() => machine.subscribe((next) => (snapshot = next)))
  $effect(() => machine.send({ type: 'SYNC_OPTIONS', orientation, primary, min, max, step, collapsible, defaultSize }))
  const api = $derived(connect(snapshot, machine.send, svelteNormalizer, { label, restMin }))
</script>

<div {...api.rootProps} style={[api.rootProps.style, style].filter(Boolean).join('; ')}>
  <div {...api.startPaneProps}>{@render first()}</div>
  <div {...api.separatorProps}><span {...api.handleProps}></span></div>
  <div {...api.endPaneProps}>{@render second()}</div>
</div>
