// packages/svelte/src/components/kv/KeyValueList.svelte
<script lang="ts" generics="T extends KeyValueItem<string>">
  import { connect, type KeyValueItem, type KeyValueListProps } from '@ggary/core/kv'
  import { svelteNormalizer } from '@ggary/core'
  import type { Snippet } from 'svelte'

  type Props = KeyValueListProps & {
    /** The pairs, in reading order. */
    items: T[]
    /** A rich value — a badge, a link, a time — drawn from its item. Without it the value is text. */
    value?: Snippet<[T]>
  }

  let { items, tight, value }: Props = $props()
  const api = $derived(connect({ tight }, svelteNormalizer))
</script>

<dl {...api.rootProps}>
  {#each items as item, index (index)}
    <dt {...api.termProps}>{item.label}</dt>
    <dd {...api.detailProps}>{#if value}{@render value(item)}{:else}{item.value ?? ''}{/if}</dd>
  {/each}
</dl>

// packages/react/src/components/kv/KeyValueList.tsx
import { Fragment, type ReactNode } from 'react'
import { connect, type KeyValueItem, type KeyValueListProps as CoreKeyValueListProps } from '@ggary/core/kv'
import { reactNormalizer } from '@ggary/core'

export interface KeyValueListProps extends CoreKeyValueListProps {
  /** The pairs, in reading order. A value may be any node: a badge, a link, a time. */
  items: KeyValueItem<ReactNode>[]
}

export function KeyValueList({ items, tight }: KeyValueListProps) {
  const api = connect({ tight }, reactNormalizer)
  return (
    <dl {...api.rootProps}>
      {items.map((item, index) => (
        // A name may repeat within one object's list, so the position keys it.
        <Fragment key={index}>
          <dt {...api.termProps}>{item.label}</dt>
          <dd {...api.detailProps}>{item.value}</dd>
        </Fragment>
      ))}
    </dl>
  )
}
