// packages/react/src/components/input/Input.tsx
import { forwardRef, type InputHTMLAttributes } from 'react'
import { connect, type InputProps as CoreInputProps } from '@ggary/core/input'
import { mergeProps, reactNormalizer } from '@ggary/core'
import { useFieldControl } from '../field/Field'

export interface InputProps
  extends CoreInputProps,
    Omit<InputHTMLAttributes<HTMLInputElement>, keyof CoreInputProps | 'value' | 'defaultValue' | 'onChange'> {
  /** Controlled. Omit and use `defaultValue` for uncontrolled. */
  value?: string
  defaultValue?: string
  onValueChange?: (value: string) => void
}

export const Input = forwardRef<HTMLInputElement, InputProps>(function Input(props, ref) {
  const {
    type, size, name, placeholder, autoComplete, inputMode, disabled, readOnly, required, invalid,
    value, defaultValue, onValueChange, ...rest
  } = props

  const api = connect(
    { type, size, name, placeholder, autoComplete, inputMode, disabled, readOnly, required, invalid },
    reactNormalizer,
    { onValueChange, field: useFieldControl() ?? undefined }
  )

  const valueProps = value !== undefined ? { value } : { defaultValue }
  // Merged, not spread: a caller's own onBlur must run alongside the Field's
  // validation handler instead of silently replacing it (or being replaced).
  return <input ref={ref} {...mergeProps(rest, api.rootProps)} {...valueProps} />
})

// packages/svelte/src/components/input/Input.svelte
<script lang="ts">
  import { connect, type InputProps } from '@ggary/core/input'
  import { mergeProps, svelteNormalizer } from '@ggary/core'
  import { getContext, untrack } from 'svelte'
  import { FIELD_CONTEXT, type FieldContext } from '../field/context'

  type Props = InputProps & {
    /** Bindable: `bind:value` is the Svelte way; a one-way `value` works too. */
    value?: string
    defaultValue?: string
    onValueChange?: (value: string) => void
    [key: string]: unknown
  }

  let {
    type,
    size,
    name,
    placeholder,
    autoComplete,
    inputMode,
    disabled,
    readOnly,
    required,
    invalid,
    value = $bindable(),
    defaultValue,
    onValueChange,
    ...rest
  }: Props = $props()

  // An uncontrolled start: defaultValue seeds the value once, at mount.
  untrack(() => {
    if (value === undefined && defaultValue !== undefined) value = defaultValue
  })

  const field = getContext<FieldContext | undefined>(FIELD_CONTEXT)

  const api = $derived(
    connect(
      { type, size, name, placeholder, autoComplete, inputMode, disabled, readOnly, required, invalid },
      svelteNormalizer,
      { onValueChange, field: field?.control }
    )
  )

  // A caller's own handlers chain with the component's instead of replacing them.
  const attrs = $derived(mergeProps(rest, api.rootProps))
</script>

<input {...attrs} bind:value />
