// packages/react/src/components/steps/Steps.tsx
import type { HTMLAttributes } from 'react'
import { connect, type StepsProps as CoreStepsProps } from '@ggary/core/steps'
import { reactNormalizer } from '@ggary/core'

export interface StepsProps extends CoreStepsProps, Omit<HTMLAttributes<HTMLOListElement>, 'children'> {}

export function Steps({ items, label, ...rest }: StepsProps) {
  const api = connect({ items, label }, reactNormalizer)
  return (
    <ol {...rest} {...api.rootProps}>
      {items.map((item, index) => {
        const parts = api.getItemProps(item)
        return (
          <li key={`${item.name}-${index}`} {...parts.itemProps}>
            <span {...parts.nameProps}>{item.name}</span>
            <span {...parts.noteProps}>{parts.note}</span>
          </li>
        )
      })}
    </ol>
  )
}

// packages/svelte/src/components/steps/Steps.svelte
<script lang="ts">
  import { connect, type StepsProps } from '@ggary/core/steps'
  import { svelteNormalizer } from '@ggary/core'

  let { items, label, ...rest }: StepsProps & { [key: string]: unknown } = $props()

  const api = $derived(connect({ items, label }, svelteNormalizer))
</script>

<ol {...rest} {...api.rootProps}>
  {#each items as item, index (item.name + index)}
    {@const parts = api.getItemProps(item)}
    <li {...parts.itemProps}>
      <span {...parts.nameProps}>{item.name}</span>
      <span {...parts.noteProps}>{parts.note}</span>
    </li>
  {/each}
</ol>
