// packages/svelte/src/components/code/CodeBlock.svelte
<script lang="ts">
  import { getConfig } from '../config-provider/context'
  import { configWords } from '@ggary/core/config-provider'
  import { COPY_IDLE, connect, createCopier, type CodeBlockProps, type CopyState } from '@ggary/core/code'
  import { svelteNormalizer } from '@ggary/core'

  type Props = CodeBlockProps & { [key: string]: unknown }

  let { code, numbered, start, label, copyValue, onCopy, words: ownWords, ...rest }: Props = $props()
  const kit = getConfig()
  const words = $derived(configWords(kit(), 'codeBlock', ownWords))

  let copy = $state<CopyState>(COPY_IDLE)
  const copier = createCopier((next) => (copy = next))
  // No timer answers into a component that has gone.
  $effect(() => () => copier.destroy())

  const api = $derived(
    connect({ code, numbered, start, label, copyValue, words, copy }, svelteNormalizer, { onCopyPress: (): void =>
      void copier.copy(api.copyText, { onCopy, words }) })
  )
</script>

<!-- One line inside the content: its whitespace is preserved, so the markup's own would show. -->
<div {...api.rootProps} {...rest}>
  <div {...api.contentProps}>{#if api.numbered}{#each api.lines as line (line.number)}<div {...api.lineProps(line)}><span {...api.lineNumberProps}>{line.number}</span><span {...api.lineSourceProps}>{line.source}</span></div>{/each}{:else}{code}{/if}</div>
  <button {...api.copyProps}><span {...api.copyIconProps}></span></button>
  <span {...api.liveProps}>{api.said}</span>
</div>

// packages/react/src/components/code/CodeBlock.tsx
import type { HTMLAttributes } from 'react'
import { connect, type CodeBlockProps as CoreCodeBlockProps } from '@ggary/core/code'
import { reactNormalizer } from '@ggary/core'
import { useCopier } from '../../utils/use-copier'
import { useConfigured } from '../config-provider'

export interface CodeBlockProps extends CoreCodeBlockProps, Omit<HTMLAttributes<HTMLDivElement>, 'onCopy'> {}

export function CodeBlock(own: CodeBlockProps) {
  const { code, numbered, start, label, copyValue, onCopy, words, ...rest } = useConfigured(own, { words: 'codeBlock' })
  const [copy, runCopy] = useCopier()
  const api = connect({ code, numbered, start, label, copyValue, words, copy }, reactNormalizer, { onCopyPress: (): void =>
    runCopy(api.copyText, { onCopy, words }) })
  return (
    <div {...api.rootProps} {...rest}>
      <div {...api.contentProps}>
        {api.numbered
          ? api.lines.map((line) => (
              <div key={line.number} {...api.lineProps(line)}>
                <span {...api.lineNumberProps}>{line.number}</span>
                <span {...api.lineSourceProps}>{line.source}</span>
              </div>
            ))
          : code}
      </div>
      <button {...api.copyProps}>
        <span {...api.copyIconProps} />
      </button>
      <span {...api.liveProps}>{api.said}</span>
    </div>
  )
}
