// packages/svelte/src/components/nav/Nav.svelte
<script lang="ts">
  import { connect, type NavItem, type NavProps } from '@ggary/core/nav'
  import { svelteNormalizer, uid } from '@ggary/core'

  /**
   * The side column. An item with `items` has sections one level down, opened
   * by the button beside it; which are open is kept here unless `open` is
   * given, and follows the reading until the reader sets it.
   */
  let { label, groups, open, onOpenChange, words, ...rest }: Omit<NavProps, 'id'> & { [key: string]: unknown } = $props()

  const id = uid('gg-nav')
  let chosen = $state<Record<string, boolean>>({})
  const api = $derived(
    connect(
      {
        id,
        label,
        groups,
        words,
        open: open ?? chosen,
        onOpenChange: (href, next) => {
          if (open === undefined) chosen = { ...chosen, [href]: next }
          onOpenChange?.(href, next)
        },
      },
      svelteNormalizer
    )
  )
</script>

{#snippet link(item: NavItem, level: 1 | 2)}
  {@const parts = api.getItemProps(item, level)}
  <a {...parts.itemProps}>{#if parts.showIcon}<span {...parts.iconProps}></span>{/if}{item.label}{#if parts.showCount}<span {...parts.countProps}>{item.count}</span>{/if}</a>
{/snippet}

<nav {...rest} {...api.rootProps}>
  {#each groups as group, index (group.label ?? index)}
    {@const parts = api.getGroupProps(group, index)}
    <div {...parts.groupProps}>
      {#if parts.showLabel}
        <span {...parts.groupLabelProps}>{group.label}</span>
      {/if}
      {#each group.items as item (item.href)}
        {@const branch = api.getBranchProps(item)}
        {#if branch}
          <div {...branch.branchProps}>
            {@render link(item, 1)}
            <button {...branch.toggleProps}><span {...branch.toggleIconProps}></span></button>
            <div {...branch.subitemsProps}>{#each branch.sections as section (section.href)}{@render link(section, 2)}{/each}</div>
          </div>
        {:else}
          {@render link(item, 1)}
        {/if}
      {/each}
    </div>
  {/each}
</nav>

// packages/react/src/components/nav/Nav.tsx
import { useId, useState, type HTMLAttributes } from 'react'
import { connect, type NavItem, type NavProps as CoreNavProps } from '@ggary/core/nav'
import { reactNormalizer } from '@ggary/core'

export interface NavProps extends Omit<CoreNavProps, 'id'>, Omit<HTMLAttributes<HTMLElement>, 'children'> {}

/**
 * The side column. An item with `items` has sections one level down, opened
 * by the button beside it; which are open is kept here unless `open` is
 * given, and follows the reading until the reader sets it.
 */
export function Nav({ label, groups, open, onOpenChange, words, ...rest }: NavProps) {
  const id = `gg-nav-${useId().replace(/:/g, '')}`
  const [chosen, setChosen] = useState<Record<string, boolean>>({})
  const api = connect(
    {
      id,
      label,
      groups,
      words,
      open: open ?? chosen,
      onOpenChange: (href, next) => {
        if (open === undefined) setChosen((current) => ({ ...current, [href]: next }))
        onOpenChange?.(href, next)
      },
    },
    reactNormalizer
  )

  const link = (item: NavItem, level: 1 | 2) => {
    const parts = api.getItemProps(item, level)
    return (
      <a key={item.href} {...parts.itemProps}>
        {parts.showIcon && <span {...parts.iconProps} />}
        {item.label}
        {parts.showCount && <span {...parts.countProps}>{item.count}</span>}
      </a>
    )
  }

  return (
    <nav {...rest} {...api.rootProps}>
      {groups.map((group, index) => {
        const parts = api.getGroupProps(group, index)
        return (
          <div key={group.label ?? index} {...parts.groupProps}>
            {parts.showLabel && <span {...parts.groupLabelProps}>{group.label}</span>}
            {group.items.map((item) => {
              const branch = api.getBranchProps(item)
              if (!branch) return link(item, 1)
              return (
                <div key={item.href} {...branch.branchProps}>
                  {link(item, 1)}
                  <button {...branch.toggleProps}>
                    <span {...branch.toggleIconProps} />
                  </button>
                  <div {...branch.subitemsProps}>{branch.sections.map((section) => link(section, 2))}</div>
                </div>
              )
            })}
          </div>
        )
      })}
    </nav>
  )
}
