// packages/svelte/src/components/segmented-control/SegmentedControl.svelte
<script lang="ts">
  import { connect, type SegmentedControlSize, type SegmentedItem } from '@ggary/core/segmented-control'
  import { onFormReset, svelteNormalizer, uid } from '@ggary/core'
  import { untrack } from 'svelte'

  type Props = {
    items: SegmentedItem[]
    label: string
    name?: string
    /** Bindable: `bind:value`. A one-way `value` works too. */
    value?: string | null
    defaultValue?: string | null
    onValueChange?: (value: string) => void
    size?: SegmentedControlSize
    disabled?: boolean
    required?: boolean
    fullWidth?: boolean
  }

  let { items, label, name, value = $bindable(), defaultValue, onValueChange, size, disabled, required, fullWidth }: Props = $props()

  const id = uid('gg-segmented')

  untrack(() => {
    if (value === undefined) value = defaultValue ?? null
  })
  const initial = untrack(() => value ?? null)

  let root: HTMLDivElement
  // A native reset rewrites the radios without an event; Svelte set `checked`
  // as a property, which is not what a reset restores to.
  $effect(() =>
    onFormReset(root, () => {
      value = initial
      for (const input of root.querySelectorAll('input')) input.checked = input.value === initial
    })
  )

  const api = $derived(
    connect({ id, items, label, name, value, size, disabled, required, fullWidth }, svelteNormalizer, {
      onValueChange: (next) => {
        value = next
        onValueChange?.(next)
      },
    })
  )
</script>

<div bind:this={root} {...api.rootProps}>
  {#each items as item, index (item.value)}
    {@const parts = api.getItemProps(item, index)}
    <label {...parts.itemProps}>
      <input {...parts.inputProps} />
      <span {...parts.textProps}>{item.label}</span>
    </label>
  {/each}
</div>

// packages/react/src/components/segmented-control/SegmentedControl.tsx
import { useId, useRef, useState } from 'react'
import { connect, type SegmentedControlSize, type SegmentedItem } from '@ggary/core/segmented-control'
import { reactNormalizer } from '@ggary/core'
import { useFormReset } from '../../utils/use-form-reset'

export interface SegmentedControlProps {
  items: SegmentedItem[]
  /** The name of the control: only the options have visible text. */
  label: string
  name?: string
  /** Controlled; omit for uncontrolled. */
  value?: string | null
  defaultValue?: string | null
  onValueChange?: (value: string) => void
  size?: SegmentedControlSize
  disabled?: boolean
  required?: boolean
  fullWidth?: boolean
}

export function SegmentedControl(props: SegmentedControlProps) {
  const { items, label, name, value, defaultValue = null, onValueChange, size, disabled, required, fullWidth } = props
  const id = `gg-segmented-${useId().replace(/:/g, '')}`
  const [uncontrolled, setUncontrolled] = useState(defaultValue)
  const controlled = value !== undefined

  const api = connect(
    { id, items, label, name, value: controlled ? value : uncontrolled, size, disabled, required, fullWidth },
    reactNormalizer,
    {
      onValueChange: (next) => {
        if (!controlled) setUncontrolled(next)
        onValueChange?.(next)
      },
    }
  )

  const root = useRef<HTMLDivElement>(null)
  useFormReset(root, () => setUncontrolled(defaultValue))

  return (
    <div ref={root} {...api.rootProps}>
      {items.map((item, index) => {
        const parts = api.getItemProps(item, index)
        return (
          <label key={item.value} {...parts.itemProps}>
            <input {...parts.inputProps} />
            <span {...parts.textProps}>{item.label}</span>
          </label>
        )
      })}
    </div>
  )
}
