// packages/react/src/components/badge/Badge.tsx
import type { HTMLAttributes, ReactNode } from 'react'
import { connect, type BadgeProps as CoreBadgeProps } from '@ggary/core/badge'
import { reactNormalizer } from '@ggary/core'

export interface BadgeProps extends CoreBadgeProps, HTMLAttributes<HTMLSpanElement> {
  /** The word. A state is always named, never only coloured. */
  children?: ReactNode
}

export function Badge({ tone, emphasis, count, dot, children, ...rest }: BadgeProps) {
  const api = connect({ tone, emphasis, count, dot }, reactNormalizer)
  return (
    <span {...api.rootProps} {...rest}>
      {api.showDot && <span {...api.dotProps} />}
      {children}
    </span>
  )
}

// packages/svelte/src/components/badge/Badge.svelte
<script lang="ts">
  import { connect, type BadgeProps } from '@ggary/core/badge'
  import { svelteNormalizer } from '@ggary/core'
  import type { Snippet } from 'svelte'

  type Props = BadgeProps & {
    /** The word. A state is always named, never only coloured. */
    children?: Snippet
    [key: string]: unknown
  }

  let { tone, emphasis, count, dot, children, ...rest }: Props = $props()
  const api = $derived(connect({ tone, emphasis, count, dot }, svelteNormalizer))
</script>

<span {...api.rootProps} {...rest}>{#if api.showDot}<span {...api.dotProps}></span>{/if}{@render children?.()}</span>
