// packages/react/src/components/copyable/Copyable.tsx
import type { HTMLAttributes } from 'react'
import { connect, type CopyableProps as CoreCopyableProps } from '@ggary/core/copyable'
import { reactNormalizer } from '@ggary/core'
import { useCopier } from '../../utils/use-copier'

export interface CopyableProps extends CoreCopyableProps, Omit<HTMLAttributes<HTMLSpanElement>, 'onCopy'> {}

export function Copyable({ value, copyValue, onCopy, words, ...rest }: CopyableProps) {
  const [copy, runCopy] = useCopier()
  const api = connect({ value, copyValue, words, copy }, reactNormalizer, { onCopyPress: (): void => runCopy(api.copyText, { onCopy, words }) })
  return (
    <span {...api.rootProps} {...rest}>
      <code {...api.valueProps}>{value}</code>
      <button {...api.copyProps}>
        <span {...api.copyIconProps} />
      </button>
      <span {...api.liveProps}>{api.said}</span>
    </span>
  )
}

// packages/svelte/src/components/copyable/Copyable.svelte
<script lang="ts">
  import { COPY_IDLE, connect, createCopier, type CopyableProps, type CopyState } from '@ggary/core/copyable'
  import { svelteNormalizer } from '@ggary/core'

  type Props = CopyableProps & { [key: string]: unknown }

  let { value, copyValue, onCopy, words, ...rest }: Props = $props()

  let copy = $state<CopyState>(COPY_IDLE)
  const copier = createCopier((next) => (copy = next))
  // No timer answers into a component that has gone.
  $effect(() => () => copier.destroy())

  const api = $derived(
    connect({ value, copyValue, words, copy }, svelteNormalizer, { onCopyPress: (): void => void copier.copy(api.copyText, { onCopy, words }) })
  )
</script>

<span {...api.rootProps} {...rest}><code {...api.valueProps}>{value}</code><button {...api.copyProps}><span {...api.copyIconProps}></span></button><span {...api.liveProps}>{api.said}</span></span>
