// packages/react/src/components/breadcrumbs/Breadcrumbs.tsx
import { createElement, type HTMLAttributes } from 'react'
import { connect, type BreadcrumbsProps as CoreBreadcrumbsProps } from '@ggary/core/breadcrumbs'
import { reactNormalizer } from '@ggary/core'

export interface BreadcrumbsProps extends CoreBreadcrumbsProps, Omit<HTMLAttributes<HTMLElement>, 'children'> {}

export function Breadcrumbs({ items, label, ...rest }: BreadcrumbsProps) {
  const api = connect({ items, label }, reactNormalizer)
  return (
    <nav {...rest} {...api.rootProps}>
      <ol {...api.listProps}>
        {items.map((item, index) => {
          const parts = api.getItemProps(item, index)
          return (
            <li key={`${item.label}-${index}`} {...parts.itemProps}>
              {createElement(parts.element, parts.linkProps, item.label)}
            </li>
          )
        })}
      </ol>
    </nav>
  )
}

// packages/svelte/src/components/breadcrumbs/Breadcrumbs.svelte
<script lang="ts">
  import { connect, type BreadcrumbsProps } from '@ggary/core/breadcrumbs'
  import { svelteNormalizer } from '@ggary/core'

  let { items, label, ...rest }: BreadcrumbsProps & { [key: string]: unknown } = $props()

  const api = $derived(connect({ items, label }, svelteNormalizer))
</script>

<nav {...rest} {...api.rootProps}>
  <ol {...api.listProps}>
    {#each items as item, index (item.label + index)}
      {@const parts = api.getItemProps(item, index)}
      <li {...parts.itemProps}>
        <svelte:element this={parts.element} {...parts.linkProps}>{item.label}</svelte:element>
      </li>
    {/each}
  </ol>
</nav>
