// packages/svelte/src/components/slider/Slider.svelte
<script lang="ts">
  import { connect, type SliderProps } from '@ggary/core/slider'
  import { mergeProps, onFormReset, svelteNormalizer, uid } from '@ggary/core'
  import { getContext, untrack } from 'svelte'
  import { FIELD_CONTEXT, type FieldContext } from '../field/context'

  type Props = Omit<SliderProps, 'id' | 'inputId' | 'value'> & {
    /** Bindable: `bind:value`. A one-way `value` works too. */
    value?: number
    defaultValue?: number
    onValueChange?: (value: number) => void
    /** The value in words, "6 agents": announced and shown instead of the number. */
    formatValue?: (value: number) => string
    [key: string]: unknown
  }

  let {
    min, max, step, name, label, valueText, showValue, size, disabled, required, invalid, marks,
    value = $bindable(), defaultValue, onValueChange, formatValue, ...rest
  }: Props = $props()

  const id = uid('gg-slider')

  untrack(() => {
    if (value === undefined && defaultValue !== undefined) value = defaultValue
  })
  const initial = untrack(() => value)

  const field = getContext<FieldContext | undefined>(FIELD_CONTEXT)

  const api = $derived(
    connect({ id, value, min, max, step, name, label, valueText, showValue, size, disabled, required, invalid, marks }, svelteNormalizer, {
      onValueChange: (next) => {
        value = next
        onValueChange?.(next)
      },
      formatValue,
      field: field?.control,
    })
  )

  let element: HTMLInputElement
  $effect(() =>
    onFormReset(element, () => {
      value = initial
      element.value = String(api.value)
    })
  )

  const attrs = $derived(mergeProps(rest, api.inputProps))
</script>

<div {...api.rootProps}>
  <input bind:this={element} {...attrs} value={api.value} />
  {#if api.showValue}
    <output {...api.outputProps}>{api.valueLabel}</output>
  {/if}
  {#if api.marks.length > 0}
    <div {...api.marksProps}>
      {#each api.marks as mark (mark.value)}<span {...api.getMarkProps(mark)}>{mark.label}</span>{/each}
    </div>
  {/if}
</div>

// packages/react/src/components/slider/Slider.tsx
import { forwardRef, useId, useRef, useState, type InputHTMLAttributes } from 'react'
import { connect, type SliderProps as CoreSliderProps } from '@ggary/core/slider'
import { mergeProps, reactNormalizer } from '@ggary/core'
import { useFieldControl } from '../field/Field'
import { useMergedRef } from '../../utils/use-merged-ref'
import { useFormReset } from '../../utils/use-form-reset'

export interface SliderProps
  extends Omit<CoreSliderProps, 'id' | 'inputId' | 'value'>,
    Omit<InputHTMLAttributes<HTMLInputElement>, keyof CoreSliderProps | 'type' | 'value' | 'defaultValue' | 'onChange' | 'size'> {
  /** Controlled. Omit and use `defaultValue` for uncontrolled. */
  value?: number
  defaultValue?: number
  onValueChange?: (value: number) => void
  /** The value in words, "6 agents": announced and shown instead of the number. */
  formatValue?: (value: number) => string
}

export const Slider = forwardRef<HTMLInputElement, SliderProps>(function Slider(props, forwardedRef) {
  const {
    min, max, step, name, label, valueText, showValue, size, disabled, required, invalid, marks,
    value, defaultValue, onValueChange, formatValue, ...rest
  } = props
  const id = `gg-slider-${useId().replace(/:/g, '')}`
  const [uncontrolled, setUncontrolled] = useState(defaultValue)
  const controlled = value !== undefined

  const api = connect(
    { id, value: controlled ? value : uncontrolled, min, max, step, name, label, valueText, showValue, size, disabled, required, invalid, marks },
    reactNormalizer,
    {
      onValueChange: (next) => {
        if (!controlled) setUncontrolled(next)
        onValueChange?.(next)
      },
      formatValue,
      field: useFieldControl() ?? undefined,
    }
  )

  const element = useRef<HTMLInputElement | null>(null)
  const ref = useMergedRef(element, forwardedRef)
  useFormReset(element, () => setUncontrolled(defaultValue))

  // The value is always React's, even uncontrolled: the fill and the number
  // beside the track follow it, so the component has to know it while dragging.
  return (
    <div {...api.rootProps}>
      <input ref={ref} {...mergeProps(rest, api.inputProps)} value={api.value} />
      {api.showValue && <output {...api.outputProps}>{api.valueLabel}</output>}
      {api.marks.length > 0 && (
        <div {...api.marksProps}>
          {api.marks.map((mark) => (
            <span key={mark.value} {...api.getMarkProps(mark)}>
              {mark.label}
            </span>
          ))}
        </div>
      )}
    </div>
  )
})
