// packages/react/src/components/empty-state/EmptyState.tsx
import type { ReactNode } from 'react'
import { connect, type EmptyStateProps as CoreEmptyStateProps } from '@ggary/core/empty-state'
import { reactNormalizer } from '@ggary/core'

export interface EmptyStateProps extends CoreEmptyStateProps {
  /** The next step: usually one button. */
  children?: ReactNode
}

export function EmptyState({ title, description, headingLevel, live, children }: EmptyStateProps) {
  const api = connect({ title, description, headingLevel, live }, reactNormalizer)
  const Title = api.titleElement
  return (
    <div {...api.rootProps}>
      <Title {...api.titleProps}>{title}</Title>
      {description !== undefined && <p {...api.descriptionProps}>{description}</p>}
      {children !== undefined && <div {...api.actionsProps}>{children}</div>}
    </div>
  )
}

// packages/svelte/src/components/empty-state/EmptyState.svelte
<script lang="ts">
  import { connect, type EmptyStateProps } from '@ggary/core/empty-state'
  import { svelteNormalizer } from '@ggary/core'
  import type { Snippet } from 'svelte'

  /* children: the next step, usually one button. */
  let { title, description, headingLevel, live, children }: EmptyStateProps & { children?: Snippet } = $props()
  const api = $derived(connect({ title, description, headingLevel, live }, svelteNormalizer))
</script>

<div {...api.rootProps}>
  <svelte:element this={api.titleElement} {...api.titleProps}>{title}</svelte:element>
  {#if description !== undefined}
    <p {...api.descriptionProps}>{description}</p>
  {/if}
  {#if children}
    <div {...api.actionsProps}>{@render children()}</div>
  {/if}
</div>
