// packages/svelte/src/components/range-slider/RangeSlider.svelte
<script lang="ts">
  import { connect, type RangeSliderProps, type RangeSliderWords, type RangeValue } from '@ggary/core/range-slider'
  import { onFormReset, svelteNormalizer, uid } from '@ggary/core'
  import { untrack } from 'svelte'
  import Input from '../input/Input.svelte'
  import InputGroup from '../input-group/InputGroup.svelte'

  type Props = Omit<RangeSliderProps, 'id' | 'value'> & {
    /** Bindable: `[lower, upper]`. A one-way `value` works too. */
    value?: RangeValue
    /** Default: the whole track. */
    defaultValue?: RangeValue
    onValueChange?: (value: RangeValue) => void
    /** A value in words, "€20": in the header, the bubbles, the marks, and what each thumb says. */
    formatValue?: (value: number) => string
    words?: RangeSliderWords
  }

  /** A range between two ends, each a thumb on one track: a price from and to, a run time from and to. */
  let { value = $bindable(), defaultValue, onValueChange, formatValue, words, ...rest }: Props = $props()

  const id = uid('gg-range')
  untrack(() => {
    if (value === undefined && defaultValue !== undefined) value = defaultValue
  })
  const initial = untrack(() => value)
  let drafts = $state<[string | null, string | null]>([null, null])

  const api = $derived(
    connect({ ...rest, id, value }, svelteNormalizer, {
      onValueChange: (next) => {
        value = next
        onValueChange?.(next)
      },
      formatValue,
      words,
      drafts,
      onDraftChange: (index, text) => (drafts = index === 0 ? [text, drafts[1]] : [drafts[0], text]),
    })
  )

  let first = $state<HTMLInputElement | null>(null)
  $effect(() =>
    onFormReset(first, () => {
      value = initial
    })
  )
</script>

{#snippet field(index: 0 | 1)}
  <InputGroup prefix={api.prefix} suffix={api.suffix} size={rest.size} disabled={rest.disabled} invalid={rest.invalid}>
    <Input {...api.getFieldProps(index)} value={api.fieldText(index)} onValueChange={(text: string) => api.onFieldInput(index, text)} />
  </InputGroup>
{/snippet}

<div {...api.rootProps}>
  <div {...api.headerProps}>
    <span {...api.labelProps}>{api.label}</span>
    {#if api.valueDisplay === 'header'}<span {...api.valueProps}>{api.valueText}</span>{/if}
  </div>
  {#if api.valueDisplay === 'bubbles'}
    <div {...api.bubblesProps}>
      {#each api.bubbles as bubble (bubble.which)}<span {...api.getBubbleProps(bubble.which)}>{bubble.text}</span>{/each}
    </div>
  {/if}
  <div {...api.controlProps}>
    <span {...api.trackProps}></span>
    <span {...api.rangeProps}></span>
    <input bind:this={first} {...api.getThumbProps(0)} />
    <input {...api.getThumbProps(1)} />
  </div>
  {#if api.marks.length > 0}
    <div {...api.marksProps}>
      {#each api.marks as mark (mark.value)}<span {...api.getMarkProps(mark)}>{mark.label}</span>{/each}
    </div>
  {/if}
  {#if api.valueDisplay === 'inputs'}
    <div {...api.fieldsProps}>
      {@render field(0)}
      <span {...api.separatorProps}>–</span>
      {@render field(1)}
    </div>
  {/if}
</div>

// packages/react/src/components/range-slider/RangeSlider.tsx
import { useId, useRef, useState } from 'react'
import { connect, type RangeSliderProps as CoreRangeSliderProps, type RangeSliderWords, type RangeValue } from '@ggary/core/range-slider'
import { reactNormalizer } from '@ggary/core'
import { Input } from '../input'
import { InputGroup } from '../input-group'
import { useFormReset } from '../../utils/use-form-reset'

export interface RangeSliderProps extends Omit<CoreRangeSliderProps, 'id' | 'value'> {
  /** Controlled: `[lower, upper]`. Omit and use `defaultValue` for uncontrolled. */
  value?: RangeValue
  /** Default: the whole track. */
  defaultValue?: RangeValue
  onValueChange?: (value: RangeValue) => void
  /** A value in words, "€20": in the header, the bubbles, the marks, and what each thumb says. */
  formatValue?: (value: number) => string
  words?: RangeSliderWords
}

/** A range between two ends, each a thumb on one track: a price from and to, a run time from and to. */
export function RangeSlider(props: RangeSliderProps) {
  const { value, defaultValue, onValueChange, formatValue, words, ...rest } = props
  const id = `gg-range-${useId().replace(/:/g, '')}`
  const [own, setOwn] = useState(defaultValue)
  const controlled = value !== undefined
  const [drafts, setDrafts] = useState<[string | null, string | null]>([null, null])

  const api = connect({ ...rest, id, value: controlled ? value : own }, reactNormalizer, {
    onValueChange: (next) => {
      if (!controlled) setOwn(next)
      onValueChange?.(next)
    },
    formatValue,
    words,
    drafts,
    onDraftChange: (index, text) => setDrafts((current) => (index === 0 ? [text, current[1]] : [current[0], text])),
  })

  const first = useRef<HTMLInputElement>(null)
  useFormReset(first, () => setOwn(defaultValue))

  // A field for each end: the kit's own Input in an InputGroup, so it looks like every other field.
  const field = (index: 0 | 1) => (
    <InputGroup prefix={api.prefix} suffix={api.suffix} size={rest.size} disabled={rest.disabled} invalid={rest.invalid}>
      <Input {...api.getFieldProps(index)} value={api.fieldText(index)} onValueChange={(text) => api.onFieldInput(index, text)} />
    </InputGroup>
  )

  return (
    <div {...api.rootProps}>
      <div {...api.headerProps}>
        <span {...api.labelProps}>{api.label}</span>
        {api.valueDisplay === 'header' && <span {...api.valueProps}>{api.valueText}</span>}
      </div>
      {api.valueDisplay === 'bubbles' && (
        <div {...api.bubblesProps}>
          {api.bubbles.map((bubble) => (
            <span key={bubble.which} {...api.getBubbleProps(bubble.which)}>
              {bubble.text}
            </span>
          ))}
        </div>
      )}
      <div {...api.controlProps}>
        <span {...api.trackProps} />
        <span {...api.rangeProps} />
        <input ref={first} {...api.getThumbProps(0)} />
        <input {...api.getThumbProps(1)} />
      </div>
      {api.marks.length > 0 && (
        <div {...api.marksProps}>
          {api.marks.map((mark) => (
            <span key={mark.value} {...api.getMarkProps(mark)}>
              {mark.label}
            </span>
          ))}
        </div>
      )}
      {api.valueDisplay === 'inputs' && (
        <div {...api.fieldsProps}>
          {field(0)}
          <span {...api.separatorProps}>–</span>
          {field(1)}
        </div>
      )}
    </div>
  )
}
