// packages/react/src/components/button/Button.tsx
import { forwardRef, type ButtonHTMLAttributes, type ReactNode } from 'react'
import { connect, type ButtonProps as CoreButtonProps } from '@ggary/core/button'
import { reactNormalizer } from '@ggary/core'

export interface ButtonProps
  extends CoreButtonProps,
    Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'type' | 'disabled'> {
  children?: ReactNode
}

/**
 * The whole adapter. This is what "thin" is supposed to mean — if it grows past
 * a screen, logic has leaked out of core.
 */
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button(props, ref) {
  const { emphasis, destructive, size, disabled, loading, fullWidth, type, children, ...rest } = props
  const api = connect({ emphasis, destructive, size, disabled, loading, fullWidth, type }, reactNormalizer)

  return (
    <button ref={ref} {...api.rootProps} {...rest}>
      {loading && <span {...api.spinnerProps} />}
      {children}
    </button>
  )
})

// packages/svelte/src/components/button/Button.svelte
<script lang="ts">
  import { connect, type ButtonProps } from '@ggary/core/button'
  import { svelteNormalizer } from '@ggary/core'
  import type { Snippet } from 'svelte'

  type Props = ButtonProps & {
    children?: Snippet
    onclick?: (event: MouseEvent) => void
    [key: string]: unknown
  }

  let {
    emphasis = 'medium',
    destructive = false,
    size = 'md',
    disabled = false,
    loading = false,
    fullWidth = false,
    type = 'button',
    children,
    ...rest
  }: Props = $props()

  // Same `connect()` React uses; only the normalizer differs.
  const api = $derived(connect({ emphasis, destructive, size, disabled, loading, fullWidth, type }, svelteNormalizer))
</script>

<button {...api.rootProps} {...rest}>
  {#if loading}<span {...api.spinnerProps}></span>{/if}
  {@render children?.()}
</button>
