// packages/svelte/src/components/checkbox/Checkbox.svelte
<script lang="ts">
  import { connect, type CheckboxProps, type CheckedState } from '@ggary/core/checkbox'
  import { mergeProps, svelteNormalizer } from '@ggary/core'
  import { getContext, untrack, type Snippet } from 'svelte'
  import { FIELD_CONTEXT, type FieldContext } from '../field/context'

  type Props = CheckboxProps & {
    /** Bindable: `bind:checked`. A one-way `checked` works too. */
    checked?: CheckedState
    defaultChecked?: CheckedState
    onCheckedChange?: (checked: boolean) => void
    /** The label text. Without it, give the input an `aria-label`. */
    children?: Snippet
    [key: string]: unknown
  }

  let {
    checked = $bindable(),
    defaultChecked,
    onCheckedChange,
    name,
    value,
    disabled,
    readOnly,
    required,
    invalid,
    children,
    ...rest
  }: Props = $props()

  untrack(() => {
    if (checked === undefined) checked = defaultChecked ?? false
  })

  const field = getContext<FieldContext | undefined>(FIELD_CONTEXT)

  const api = $derived(
    connect({ checked, name, value, disabled, readOnly, required, invalid }, svelteNormalizer, {
      onCheckedChange: (next) => {
        checked = next
        onCheckedChange?.(next)
      },
      field: field?.control,
    })
  )

  const attrs = $derived(mergeProps(rest, api.inputProps))

  let element: HTMLInputElement
  // A property, not an attribute: no prop bag can carry it.
  $effect(() => {
    element.indeterminate = api.indeterminate
  })
</script>

<label {...api.rootProps}>
  <span {...api.controlProps}>
    <input bind:this={element} {...attrs} />
    <span {...api.indicatorProps}></span>
  </span>
  {#if children}
    <span {...api.labelProps}>{@render children()}</span>
  {/if}
</label>

// packages/react/src/components/checkbox/Checkbox.tsx
import { forwardRef, useLayoutEffect, useRef, useState, type InputHTMLAttributes, type ReactNode } from 'react'
import { connect, type CheckboxProps as CoreCheckboxProps, type CheckedState } from '@ggary/core/checkbox'
import { mergeProps, reactNormalizer } from '@ggary/core'
import { useFieldControl } from '../field/Field'
import { useMergedRef } from '../../utils/use-merged-ref'

export interface CheckboxProps
  extends CoreCheckboxProps,
    Omit<InputHTMLAttributes<HTMLInputElement>, keyof CoreCheckboxProps | 'type' | 'defaultChecked' | 'onChange' | 'children'> {
  /** Controlled. Omit and use `defaultChecked` for uncontrolled. */
  checked?: CheckedState
  defaultChecked?: CheckedState
  onCheckedChange?: (checked: boolean) => void
  /** The label text. Without it, give the input an `aria-label`. */
  children?: ReactNode
}

/** Other props go to the native input, which is the focusable, labelled control. */
export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(function Checkbox(props, forwardedRef) {
  const {
    checked, defaultChecked = false, onCheckedChange, name, value, disabled, readOnly, required, invalid, children, ...rest
  } = props

  const [uncontrolled, setUncontrolled] = useState<CheckedState>(defaultChecked)
  const controlled = checked !== undefined

  const api = connect(
    { checked: controlled ? checked : uncontrolled, name, value, disabled, readOnly, required, invalid },
    reactNormalizer,
    {
      onCheckedChange: (next) => {
        if (!controlled) setUncontrolled(next)
        onCheckedChange?.(next)
      },
      field: useFieldControl() ?? undefined,
      // React puts a controlled input back after every event; see utils/choice.
      restoresChecked: true,
    }
  )

  const element = useRef<HTMLInputElement | null>(null)
  const ref = useMergedRef(element, forwardedRef)

  // A property, not an attribute: no prop bag can carry it.
  useLayoutEffect(() => {
    if (element.current) element.current.indeterminate = api.indeterminate
  }, [api.indeterminate])

  return (
    <label {...api.rootProps}>
      <span {...api.controlProps}>
        <input ref={ref} {...mergeProps(rest, api.inputProps)} />
        <span {...api.indicatorProps} />
      </span>
      {children != null && <span {...api.labelProps}>{children}</span>}
    </label>
  )
})
