// packages/svelte/src/components/button-group/ButtonGroup.svelte
<script lang="ts">
  import { connect, type ButtonGroupProps } from '@ggary/core/button-group'
  import { svelteNormalizer } from '@ggary/core'
  import type { Snippet } from 'svelte'

  let { size, label, children }: ButtonGroupProps & { children: Snippet } = $props()

  const api = $derived(connect({ size, label }, svelteNormalizer))
</script>

<div {...api.rootProps}>{@render children()}</div>

// packages/react/src/components/button-group/ButtonGroup.tsx
import type { HTMLAttributes, ReactNode } from 'react'
import { connect, type ButtonGroupProps as CoreButtonGroupProps } from '@ggary/core/button-group'
import { reactNormalizer } from '@ggary/core'

export interface ButtonGroupProps extends CoreButtonGroupProps, HTMLAttributes<HTMLDivElement> {
  children: ReactNode
}

export function ButtonGroup({ size, label, children, ...rest }: ButtonGroupProps) {
  const api = connect({ size, label }, reactNormalizer)
  return (
    <div {...rest} {...api.rootProps}>
      {children}
    </div>
  )
}
