// packages/svelte/src/components/tree/Tree.svelte
<script lang="ts">
  import { connect, createTreeMachine, type TreeNode, type TreeSelectionMode } from '@ggary/core/tree'
  import { rovingFocus, scrollIntoViewIfNeeded, svelteNormalizer, uid } from '@ggary/core'
  import { untrack, type Snippet } from 'svelte'

  type Props = {
    items: TreeNode[]
    /** The tree's accessible name. */
    label: string
    /** Bindable: the chosen nodes. */
    value?: string[]
    defaultValue?: string[]
    onValueChange?: (value: string[]) => void
    /** Bindable: the open branches. */
    expanded?: string[]
    defaultExpanded?: string[]
    onExpandedChange?: (expanded: string[]) => void
    /** `single` (default), `multiple`, or `none` for a tree only walked and opened. */
    selectionMode?: TreeSelectionMode
    disabled?: boolean
    /** Draws a row's text; default the label. An icon before it, a count after. */
    row?: Snippet<[TreeNode]>
  }

  /** Nested items, a branch opened in place. */
  let {
    items,
    label,
    value = $bindable(),
    defaultValue,
    onValueChange,
    expanded = $bindable(),
    defaultExpanded,
    onExpandedChange,
    selectionMode,
    disabled,
    row,
  }: Props = $props()

  const machine = untrack(() =>
    createTreeMachine({
      id: uid('gg-tree'),
      items,
      defaultValue: value !== undefined ? value : defaultValue,
      defaultExpanded: expanded !== undefined ? expanded : defaultExpanded,
      selectionMode,
      disabled,
      onValueChange: (next) => {
        value = next
        onValueChange?.(next)
      },
      onExpandedChange: (next) => {
        expanded = next
        onExpandedChange?.(next)
      },
    })
  )
  let snapshot = $state.raw(machine.getState())
  $effect(() => machine.subscribe((next) => (snapshot = next)))
  const api = $derived(connect(snapshot, machine.send, svelteNormalizer, { label }))

  $effect(() => machine.send({ type: 'SYNC_ITEMS', items }))
  $effect(() => machine.send({ type: 'SYNC_OPTIONS', selectionMode, disabled }))
  $effect(() => {
    if (value !== undefined) machine.send({ type: 'SYNC_VALUE', value })
  })
  $effect(() => {
    if (expanded !== undefined) machine.send({ type: 'SYNC_EXPANDED', expanded })
  })

  let rootEl = $state<HTMLDivElement | null>(null)
  let lastFocusNonce = 0
  $effect(() => {
    const { focusNonce, focusValue } = api
    if (focusNonce === 0 || focusNonce === lastFocusNonce || focusValue === null) return
    lastFocusNonce = focusNonce
    untrack(() => {
      const itemId = api.ids.item(focusValue)
      rovingFocus(document, itemId)
      scrollIntoViewIfNeeded(document.getElementById(itemId), rootEl)
    })
  })
</script>

<div bind:this={rootEl} {...api.rootProps}>
  {#each api.rows as entry (entry.node.value)}
    <div {...api.getItemProps(entry)}>
      <span {...api.getToggleProps(entry)}></span>
      <span {...api.itemTextProps}>{#if row}{@render row(entry.node)}{:else}{entry.node.label}{/if}</span>
      {#if snapshot.selectionMode === 'multiple'}<span {...api.itemIndicatorProps}></span>{/if}
    </div>
  {/each}
</div>

// packages/react/src/components/tree/Tree.tsx
import { useEffect, useId, useLayoutEffect, useRef, useState, useSyncExternalStore, type ReactNode } from 'react'
import { connect, createTreeMachine, type TreeNode, type TreeSelectionMode } from '@ggary/core/tree'
import { reactNormalizer, rovingFocus, scrollIntoViewIfNeeded } from '@ggary/core'

export interface TreeProps {
  items: TreeNode[]
  /** The tree's accessible name. */
  label: string
  /** Controlled: the chosen nodes. Omit and use `defaultValue` for uncontrolled. */
  value?: string[]
  defaultValue?: string[]
  onValueChange?: (value: string[]) => void
  /** Controlled: the open branches. Omit and use `defaultExpanded` for uncontrolled. */
  expanded?: string[]
  defaultExpanded?: string[]
  onExpandedChange?: (expanded: string[]) => void
  /** `single` (default), `multiple`, or `none` for a tree only walked and opened. */
  selectionMode?: TreeSelectionMode
  disabled?: boolean
  /** Draws a row's text; default the label. An icon before it, a count after. */
  children?: (node: TreeNode) => ReactNode
}

/** Nested items, a branch opened in place. */
export function Tree(props: TreeProps) {
  const { items, label, value, defaultValue, onValueChange, expanded, defaultExpanded, onExpandedChange, selectionMode, disabled, children } = props
  const id = `gg-tree-${useId().replace(/:/g, '')}`
  const callbacks = useRef({ onValueChange, onExpandedChange })
  callbacks.current = { onValueChange, onExpandedChange }
  const [machine] = useState(() =>
    createTreeMachine({
      id, items, value, defaultValue, expanded, defaultExpanded, selectionMode, disabled,
      onValueChange: (next) => callbacks.current.onValueChange?.(next),
      onExpandedChange: (next) => callbacks.current.onExpandedChange?.(next),
    })
  )
  const state = useSyncExternalStore(machine.subscribe, machine.getState, machine.getState)
  const api = connect(state, machine.send, reactNormalizer, { label })

  useEffect(() => machine.send({ type: 'SYNC_ITEMS', items }), [machine, items])
  useEffect(() => machine.send({ type: 'SYNC_OPTIONS', selectionMode, disabled }), [machine, selectionMode, disabled])
  useEffect(() => {
    if (value !== undefined) machine.send({ type: 'SYNC_VALUE', value })
  }, [machine, value])
  useEffect(() => {
    if (expanded !== undefined) machine.send({ type: 'SYNC_EXPANDED', expanded })
  }, [machine, expanded])

  const rootRef = useRef<HTMLDivElement>(null)
  const lastFocusNonce = useRef(0)
  useLayoutEffect(() => {
    if (api.focusNonce === 0 || api.focusNonce === lastFocusNonce.current || api.focusValue === null) return
    lastFocusNonce.current = api.focusNonce
    const itemId = api.ids.item(api.focusValue)
    rovingFocus(document, itemId)
    scrollIntoViewIfNeeded(document.getElementById(itemId), rootRef.current)
  })

  return (
    <div ref={rootRef} {...api.rootProps}>
      {api.rows.map((row) => (
        <div key={row.node.value} {...api.getItemProps(row)}>
          <span {...api.getToggleProps(row)} />
          <span {...api.itemTextProps}>{children ? children(row.node) : row.node.label}</span>
          {state.selectionMode === 'multiple' && <span {...api.itemIndicatorProps} />}
        </div>
      ))}
    </div>
  )
}
