// packages/svelte/src/components/chip-group/ChipGroup.svelte
<script lang="ts">
  import {
    connect,
    createChipGroupMachine,
    type ChipGroupMode,
    type ChipGroupOrientation,
    type ChipItem,
  } from '@ggary/core/chip-group'
  import type { ChipSize, ChipVariant } from '@ggary/core/chip'
  import { rovingFocus, svelteNormalizer, uid } from '@ggary/core'
  import RemoveIcon from '../chip/RemoveIcon.svelte'

  type Props = {
    items: ChipItem[]
    label?: string
    mode?: ChipGroupMode
    orientation?: ChipGroupOrientation
    variant?: ChipVariant
    size?: ChipSize
    removable?: boolean
    disabled?: boolean
    name?: string
    value?: string[]
    defaultValue?: string[]
    onSelectionChange?: (selection: string[], items: ChipItem[]) => void
    onRemove?: (value: string, item: ChipItem | null) => void
    emptyLabel?: string
  }

  let {
    items,
    label,
    mode,
    orientation,
    variant,
    size,
    removable = false,
    disabled = false,
    name,
    value,
    defaultValue,
    onSelectionChange,
    onRemove,
    emptyLabel = 'Nothing here',
  }: Props = $props()

  const id = uid('gg-chips')

  const machine = createChipGroupMachine({
    id,
    items,
    mode,
    orientation,
    disabled,
    removable,
    value,
    defaultValue,
    onSelectionChange: (selection, selected) => onSelectionChange?.(selection, selected),
    onRemove: (removedValue, item) => onRemove?.(removedValue, item),
  })

  let snapshot = $state(machine.getState())
  $effect(() => machine.subscribe((next) => (snapshot = next)))

  const api = $derived(connect(snapshot, machine.send, svelteNormalizer, { label, variant, size, name }))

  $effect(() => machine.send({ type: 'SYNC_ITEMS', items }))
  $effect(() => machine.send({ type: 'SYNC_DISABLED', disabled }))
  $effect(() => {
    if (value !== undefined) machine.send({ type: 'SYNC_SELECTION', selection: value })
  })

  // Identical rule to the React adapter: act on the nonce, and only when it
  // actually changed. `api` is re-derived on every state change, so an effect
  // that merely reads it would re-focus constantly and steal focus back from
  // wherever the user moved it.
  let lastFocusNonce = 0
  $effect(() => {
    const { nonce, index } = snapshot.focus
    if (nonce === 0 || nonce === lastFocusNonce || index < 0) return
    lastFocusNonce = nonce
    rovingFocus(document, api.ids.chip(index))
  })
</script>

<div {...api.rootProps}>
  {#if label}
    <span {...api.labelProps}>{label}</span>
  {/if}

  <div {...api.listProps}>
    {#if api.items.length === 0}
      <span {...api.emptyProps}>{emptyLabel}</span>
    {/if}
    {#each api.items as item, index (item.value)}
      <button {...api.getChipProps(item, index)}>
        <span {...api.getChipLabelProps()}>{item.label}</span>
        {#if item.removable ?? removable}
          <span {...api.getChipRemoveProps(item, index)}><RemoveIcon /></span>
        {/if}
      </button>
    {/each}
  </div>

  {#if api.hasName}
    {#each api.selection as selected (selected)}
      <input {...api.getHiddenInputProps(selected)} />
    {/each}
  {/if}
</div>

// packages/react/src/components/chip-group/ChipGroup.tsx
import { useEffect, useId, useLayoutEffect, useRef, useState, useSyncExternalStore } from 'react'
import { connect, createChipGroupMachine, type ChipGroupMode, type ChipGroupOrientation, type ChipItem } from '@ggary/core/chip-group'
import type { ChipSize, ChipVariant } from '@ggary/core/chip'
import { reactNormalizer, rovingFocus } from '@ggary/core'
import { RemoveIcon } from '../chip/Chip'

export interface ChipGroupProps {
  items: ChipItem[]
  label?: string
  mode?: ChipGroupMode
  orientation?: ChipGroupOrientation
  variant?: ChipVariant
  size?: ChipSize
  removable?: boolean
  disabled?: boolean
  name?: string
  /** Controlled. Omit and use `defaultValue` for uncontrolled. */
  value?: string[]
  defaultValue?: string[]
  onSelectionChange?: (selection: string[], items: ChipItem[]) => void
  onRemove?: (value: string, item: ChipItem | null) => void
  emptyLabel?: string
}

export function ChipGroup(props: ChipGroupProps) {
  const {
    items, label, mode, orientation, variant, size, removable, disabled = false,
    name, value, defaultValue, onSelectionChange, onRemove, emptyLabel = 'Nothing here',
  } = props

  const id = `gg-chips-${useId().replace(/:/g, '')}`

  const callbacks = useRef({ onSelectionChange, onRemove })
  callbacks.current = { onSelectionChange, onRemove }

  const [machine] = useState(() =>
    createChipGroupMachine({
      id, items, mode, orientation, disabled, removable, value, defaultValue,
      onSelectionChange: (selection, selected) => callbacks.current.onSelectionChange?.(selection, selected),
      onRemove: (removedValue, item) => callbacks.current.onRemove?.(removedValue, item),
    })
  )

  const state = useSyncExternalStore(machine.subscribe, machine.getState, machine.getState)
  const api = connect(state, machine.send, reactNormalizer, { label, variant, size, name })

  useEffect(() => machine.send({ type: 'SYNC_ITEMS', items }), [machine, items])
  useEffect(() => machine.send({ type: 'SYNC_DISABLED', disabled }), [machine, disabled])
  useEffect(() => {
    if (value !== undefined) machine.send({ type: 'SYNC_SELECTION', selection: value })
  }, [machine, value])

  // The one piece of DOM work roving tabindex needs, and it has two traps.
  //
  // useLayoutEffect, not useEffect: focus must land before paint. A passive
  // effect moves it a frame late, and under concurrent rendering can be
  // delayed further.
  //
  // Guard on the nonce explicitly rather than trusting the dep array: `api.ids`
  // is a fresh object every render, so a dep-array version re-runs constantly
  // and will drag focus back into the group from wherever the user actually
  // moved it.
  const lastFocusNonce = useRef(0)
  useLayoutEffect(() => {
    if (api.focusNonce === 0 || api.focusNonce === lastFocusNonce.current || api.focusedIndex < 0) return
    lastFocusNonce.current = api.focusNonce
    rovingFocus(document, api.ids.chip(api.focusedIndex))
  })

  return (
    <div {...api.rootProps}>
      {label && <span {...api.labelProps}>{label}</span>}

      <div {...api.listProps}>
        {api.items.length === 0 && <span {...api.emptyProps}>{emptyLabel}</span>}
        {api.items.map((item, index) => (
          <button key={item.value} {...api.getChipProps(item, index)}>
            <span {...api.getChipLabelProps()}>{item.label}</span>
            {(item.removable ?? removable) && (
              <span {...api.getChipRemoveProps(item, index)}>
                <RemoveIcon />
              </span>
            )}
          </button>
        ))}
      </div>

      {api.hasName && api.selection.map((v) => <input key={v} {...api.getHiddenInputProps(v)} />)}
    </div>
  )
}
