// apps/docs/src/pages/metric/Metric.tsx
import { Metric, MetricRow } from '@ggary/react'
import { DemoPage, Specimen } from '../../react/DemoPage'
import { headlineMetrics, runMetrics, singles } from './data'

const ROWS = [
  { label: 'MetricRow', joined: false, headline: false, metrics: runMetrics },
  { label: 'MetricRow joined', joined: true, headline: false, metrics: runMetrics },
  { label: 'MetricRow joined headline', joined: true, headline: true, metrics: headlineMetrics },
]

export default function MetricPage() {
  return (
    <DemoPage
      variants={singles.map(({ made, metric }) => (
        <Specimen key={made} label={made}>
          <Metric {...metric} locale="en-GB" />
        </Specimen>
      ))}
      composition={ROWS.map(({ label, joined, headline, metrics }) => (
        <Specimen key={label} label={label} wide>
          <MetricRow joined={joined} headline={headline}>
            {metrics.map((metric) => (
              <Metric key={metric.label} {...metric} locale="en-GB" />
            ))}
          </MetricRow>
        </Specimen>
      ))}
    />
  )
}

// apps/docs/src/pages/metric/Metric.svelte
<script lang="ts">
  import { Metric, MetricRow } from '@ggary/svelte'
  import DemoPage from '../../svelte/DemoPage.svelte'
  import Specimen from '../../svelte/Specimen.svelte'
  import { headlineMetrics, runMetrics, singles } from './data'

  const ROWS = [
    { label: 'MetricRow', joined: false, headline: false, metrics: runMetrics },
    { label: 'MetricRow joined', joined: true, headline: false, metrics: runMetrics },
    { label: 'MetricRow joined headline', joined: true, headline: true, metrics: headlineMetrics },
  ]
</script>

<DemoPage>
  {#snippet variants()}
    {#each singles as { made, metric } (made)}
      <Specimen label={made}><Metric {...metric} locale="en-GB" /></Specimen>
    {/each}
  {/snippet}
  {#snippet composition()}
    {#each ROWS as { label, joined, headline, metrics } (label)}
      <Specimen {label} wide>
        <MetricRow {joined} {headline}>
          {#each metrics as metric (metric.label)}<Metric {...metric} locale="en-GB" />{/each}
        </MetricRow>
      </Specimen>
    {/each}
  {/snippet}
</DemoPage>
