// packages/react/src/components/result/Result.tsx
import type { ReactNode } from 'react'
import { connect, type ResultProps as CoreResultProps } from '@ggary/core/result'
import { reactNormalizer } from '@ggary/core'

export interface ResultProps extends CoreResultProps {
  /** The next step: a button or two. */
  actions?: ReactNode
  /** Detail under the next step: what failed, a reference number. */
  children?: ReactNode
}

export function Result({ tone, title, description, code, headingLevel, live, actions, children }: ResultProps) {
  const api = connect({ tone, title, description, code, headingLevel, live }, reactNormalizer)
  const Title = api.titleElement
  return (
    <div {...api.rootProps}>
      {api.showCode ? <span {...api.codeProps}>{code}</span> : <span {...api.iconProps} />}
      <Title {...api.titleProps}>{title}</Title>
      {description !== undefined && <p {...api.descriptionProps}>{description}</p>}
      {actions != null && <div {...api.actionsProps}>{actions}</div>}
      {children != null && <div {...api.detailsProps}>{children}</div>}
    </div>
  )
}

// packages/svelte/src/components/result/Result.svelte
<script lang="ts">
  import { connect, type ResultProps } from '@ggary/core/result'
  import { svelteNormalizer } from '@ggary/core'
  import type { Snippet } from 'svelte'

  let { tone, title, description, code, headingLevel, live, actions, children }: ResultProps & { actions?: Snippet; children?: Snippet } = $props()
  const api = $derived(connect({ tone, title, description, code, headingLevel, live }, svelteNormalizer))
</script>

<div {...api.rootProps}>
  {#if api.showCode}<span {...api.codeProps}>{code}</span>{:else}<span {...api.iconProps}></span>{/if}
  <svelte:element this={api.titleElement} {...api.titleProps}>{title}</svelte:element>
  {#if description !== undefined}<p {...api.descriptionProps}>{description}</p>{/if}
  {#if actions}<div {...api.actionsProps}>{@render actions()}</div>{/if}
  {#if children}<div {...api.detailsProps}>{@render children()}</div>{/if}
</div>
