// packages/react/src/components/checkbox-group/CheckboxGroup.tsx
import { useId, useLayoutEffect, useRef, useState } from 'react'
import { connect, type CheckboxGroupOrientation, type CheckboxItem } from '@ggary/core/checkbox-group'
import { reactNormalizer } from '@ggary/core'
import { useFieldsetGroup } from '../fieldset/Fieldset'

export interface CheckboxGroupProps {
  items: CheckboxItem[]
  name?: string
  /** Controlled. Omit and use `defaultValue` for uncontrolled. */
  value?: string[]
  defaultValue?: string[]
  onValueChange?: (value: string[]) => void
  label?: string
  orientation?: CheckboxGroupOrientation
  disabled?: boolean
  /** At least one checked. */
  required?: boolean
  invalid?: boolean
  requiredMessage?: string
}

export function CheckboxGroup(props: CheckboxGroupProps) {
  const {
    items, name, value, defaultValue = [], onValueChange, label, orientation, disabled, required, invalid, requiredMessage,
  } = props
  const id = `gg-checkboxes-${useId().replace(/:/g, '')}`

  const [uncontrolled, setUncontrolled] = useState(defaultValue)
  const controlled = value !== undefined

  const api = connect(
    { id, items, name, value: controlled ? value : uncontrolled, label, orientation, disabled, required, invalid, requiredMessage },
    reactNormalizer,
    {
      onValueChange: (next) => {
        if (!controlled) setUncontrolled(next)
        onValueChange?.(next)
      },
      restoresChecked: true,
      group: useFieldsetGroup() ?? undefined,
    }
  )

  // "At least one" has no attribute; it is a custom validity on the first box.
  const list = useRef<HTMLDivElement>(null)
  useLayoutEffect(() => {
    list.current?.querySelector('input')?.setCustomValidity(api.validationMessage)
  }, [api.validationMessage, items])

  return (
    <div {...api.rootProps}>
      {label && <span {...api.labelProps}>{label}</span>}
      <div ref={list} {...api.listProps}>
        {items.map((item, index) => {
          const parts = api.getItemProps(item, index)
          return (
            <label key={item.value} {...parts.rootProps}>
              <span {...parts.controlProps}>
                <input {...parts.inputProps} />
                <span {...parts.indicatorProps} />
              </span>
              <span {...parts.labelProps}>{item.label}</span>
            </label>
          )
        })}
      </div>
    </div>
  )
}

// packages/svelte/src/components/checkbox-group/CheckboxGroup.svelte
<script lang="ts">
  import { connect, type CheckboxGroupOrientation, type CheckboxItem } from '@ggary/core/checkbox-group'
  import { svelteNormalizer, uid } from '@ggary/core'
  import { getContext, untrack } from 'svelte'
  import { FIELDSET_CONTEXT, type FieldsetContext } from '../fieldset/context'

  type Props = {
    items: CheckboxItem[]
    name?: string
    /** Bindable: `bind:value`. A one-way `value` works too. */
    value?: string[]
    defaultValue?: string[]
    onValueChange?: (value: string[]) => void
    label?: string
    orientation?: CheckboxGroupOrientation
    disabled?: boolean
    /** At least one checked. */
    required?: boolean
    invalid?: boolean
    requiredMessage?: string
  }

  let {
    items,
    name,
    value = $bindable(),
    defaultValue,
    onValueChange,
    label,
    orientation,
    disabled,
    required,
    invalid,
    requiredMessage,
  }: Props = $props()

  const id = uid('gg-checkboxes')

  untrack(() => {
    if (value === undefined) value = defaultValue ?? []
  })

  const fieldset = getContext<FieldsetContext | undefined>(FIELDSET_CONTEXT)

  const api = $derived(
    connect(
      { id, items, name, value, label, orientation, disabled, required, invalid, requiredMessage },
      svelteNormalizer,
      {
        onValueChange: (next) => {
          value = next
          onValueChange?.(next)
        },
        group: fieldset?.group,
      }
    )
  )

  // "At least one" has no attribute; it is a custom validity on the first box.
  let list: HTMLDivElement
  $effect(() => {
    const message = api.validationMessage
    void items
    list.querySelector('input')?.setCustomValidity(message)
  })
</script>

<div {...api.rootProps}>
  {#if label}
    <span {...api.labelProps}>{label}</span>
  {/if}
  <div bind:this={list} {...api.listProps}>
    {#each items as item, index (item.value)}
      {@const parts = api.getItemProps(item, index)}
      <label {...parts.rootProps}>
        <span {...parts.controlProps}>
          <input {...parts.inputProps} />
          <span {...parts.indicatorProps}></span>
        </span>
        <span {...parts.labelProps}>{item.label}</span>
      </label>
    {/each}
  </div>
</div>
