// packages/react/src/components/run/Run.tsx
import type { HTMLAttributes } from 'react'
import { connect, type RunProps as CoreRunProps, type RunWords } from '@ggary/core/run'
import { reactNormalizer } from '@ggary/core'

export interface RunProps extends CoreRunProps, Omit<HTMLAttributes<HTMLSpanElement>, 'children'> {
  /** The fixed text of the reading. */
  words?: Partial<RunWords>
}

/** The countable units of one run: phases, attempts or shards, each carrying its own outcome. */
export function Run({ units, label, showValue, locale, words, ...rest }: RunProps) {
  const api = connect({ units, label, showValue, locale }, reactNormalizer, { words })
  return (
    <span {...rest} {...api.rootProps}>
      <span {...api.unitsProps}>
        {api.units.map((unit) => (
          <span key={unit.key} {...unit.dotProps} />
        ))}
      </span>
      {api.showValue && <span {...api.valueProps}>{api.valueText}</span>}
    </span>
  )
}

// packages/svelte/src/components/run/Run.svelte
<script lang="ts">
  import { connect, type RunProps, type RunWords } from '@ggary/core/run'
  import { svelteNormalizer } from '@ggary/core'

  type Props = RunProps & {
    /** The fixed text of the reading. */
    words?: Partial<RunWords>
    [key: string]: unknown
  }

  /** The countable units of one run: phases, attempts or shards, each carrying its own outcome. */
  let { units, label, showValue, locale, words, ...rest }: Props = $props()
  const api = $derived(connect({ units, label, showValue, locale }, svelteNormalizer, words))
</script>

<span {...rest} {...api.rootProps}>
  <span {...api.unitsProps}>
    {#each api.units as unit (unit.key)}<span {...unit.dotProps}></span>{/each}
  </span>
  {#if api.showValue}<span {...api.valueProps}>{api.valueText}</span>{/if}
</span>
