// packages/svelte/src/components/sparkline/Sparkline.svelte
<script lang="ts">
  import { connect, type SparklineProps, type SparklineWords } from '@ggary/core/sparkline'
  import { svelteNormalizer } from '@ggary/core'

  /* words: the default reading in another language. */
  type Props = SparklineProps & {
    words?: Partial<SparklineWords>
    [key: string]: unknown
  }

  let { values, area, last, series, label, describe, locale, words, ...rest }: Props = $props()
  const api = $derived(connect({ values, area, last, series, label, describe, locale }, svelteNormalizer, { words }))
</script>

<!-- The fill first, the line over it, the dot of the last value last: the order of the nodes is the order of drawing. -->
<svg {...api.rootProps} {...rest}>
  {#if api.showArea}<path {...api.areaProps}></path>{/if}
  {#if !api.empty}<path {...api.lineProps}></path>{/if}
  {#if api.showLast}<circle {...api.lastProps}></circle>{/if}
</svg>

// packages/react/src/components/sparkline/Sparkline.tsx
import type { SVGAttributes } from 'react'
import { connect, type SparklineProps as CoreSparklineProps, type SparklineWords } from '@ggary/core/sparkline'
import { reactNormalizer } from '@ggary/core'

export interface SparklineProps extends CoreSparklineProps, Omit<SVGAttributes<SVGSVGElement>, 'values'> {
  /** The default reading in another language. */
  words?: Partial<SparklineWords>
}

/**
 * The shape of a change beside a number. The geometry is core's; this draws
 * it in the order it must be drawn — the fill, the line over it, the dot of
 * the last value last — and nothing else.
 */
export function Sparkline({ values, area, last, series, label, describe, locale, words, ...rest }: SparklineProps) {
  const api = connect({ values, area, last, series, label, describe, locale }, reactNormalizer, { words })
  return (
    <svg {...api.rootProps} {...rest}>
      {api.showArea && <path {...api.areaProps} />}
      {!api.empty && <path {...api.lineProps} />}
      {api.showLast && <circle {...api.lastProps} />}
    </svg>
  )
}
