// packages/react/src/components/textarea/Textarea.tsx
import { forwardRef, useLayoutEffect, useRef, type TextareaHTMLAttributes } from 'react'
import { connect, type TextareaProps as CoreTextareaProps } from '@ggary/core/textarea'
import { attachAutosize, mergeProps, reactNormalizer, type Autosize } from '@ggary/core'
import { useFieldControl } from '../field/Field'
import { useMergedRef } from '../../utils/use-merged-ref'

export interface TextareaProps
  extends CoreTextareaProps,
    Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, keyof CoreTextareaProps | 'value' | 'defaultValue' | 'onChange'> {
  /** Controlled. Omit and use `defaultValue` for uncontrolled. */
  value?: string
  defaultValue?: string
  onValueChange?: (value: string) => void
}

export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(function Textarea(props, forwardedRef) {
  const {
    size, name, placeholder, rows, minLength, maxLength, autoComplete, disabled, readOnly, required, invalid,
    resize, autoResize, maxRows, value, defaultValue, onValueChange, ...rest
  } = props

  const api = connect(
    { size, name, placeholder, rows, minLength, maxLength, autoComplete, disabled, readOnly, required, invalid, resize, autoResize, maxRows },
    reactNormalizer,
    { onValueChange, field: useFieldControl() ?? undefined }
  )

  const element = useRef<HTMLTextAreaElement | null>(null)
  const autosize = useRef<Autosize | null>(null)

  const ref = useMergedRef(element, forwardedRef)

  // Layout effects, so the first paint already has the measured height.
  useLayoutEffect(() => {
    if (!api.autosize || !element.current) return
    const instance = attachAutosize(element.current, api.autosize)
    autosize.current = instance
    return () => {
      instance.destroy()
      autosize.current = null
    }
  }, [autoResize])

  useLayoutEffect(() => autosize.current?.setOptions({ maxRows }), [maxRows])

  // A value pushed by the owner fires no input event, so nothing re-measured it.
  useLayoutEffect(() => autosize.current?.update(), [value])

  const valueProps = value !== undefined ? { value } : { defaultValue }
  return <textarea ref={ref} {...mergeProps(rest, api.rootProps)} {...valueProps} />
})

// packages/svelte/src/components/textarea/Textarea.svelte
<script lang="ts">
  import { connect, type TextareaProps } from '@ggary/core/textarea'
  import { attachAutosize, mergeProps, svelteNormalizer, type Autosize } from '@ggary/core'
  import { getContext, untrack } from 'svelte'
  import { FIELD_CONTEXT, type FieldContext } from '../field/context'

  type Props = TextareaProps & {
    /** Bindable: `bind:value` is the Svelte way; a one-way `value` works too. */
    value?: string
    defaultValue?: string
    onValueChange?: (value: string) => void
    [key: string]: unknown
  }

  let {
    size,
    name,
    placeholder,
    rows,
    minLength,
    maxLength,
    autoComplete,
    disabled,
    readOnly,
    required,
    invalid,
    resize,
    autoResize,
    maxRows,
    value = $bindable(),
    defaultValue,
    onValueChange,
    ...rest
  }: Props = $props()

  untrack(() => {
    if (value === undefined && defaultValue !== undefined) value = defaultValue
  })

  const field = getContext<FieldContext | undefined>(FIELD_CONTEXT)

  const api = $derived(
    connect(
      { size, name, placeholder, rows, minLength, maxLength, autoComplete, disabled, readOnly, required, invalid, resize, autoResize, maxRows },
      svelteNormalizer,
      { onValueChange, field: field?.control }
    )
  )

  const attrs = $derived(mergeProps(rest, api.rootProps))

  let element: HTMLTextAreaElement
  // Not state: the effects below must depend on the props, not on this handle.
  let autosize: Autosize | null = null

  $effect(() => {
    if (!autoResize) return
    const instance = untrack(() => attachAutosize(element, { maxRows }))
    autosize = instance
    return () => {
      instance.destroy()
      autosize = null
    }
  })

  $effect(() => {
    const options = { maxRows }
    untrack(() => autosize?.setOptions(options))
  })

  // A value set from outside fires no input event, so nothing re-measured it.
  $effect(() => {
    void value
    untrack(() => autosize?.update())
  })
</script>

<textarea bind:this={element} {...attrs} bind:value></textarea>
