// packages/react/src/components/history/History.tsx
import type { HTMLAttributes } from 'react'
import { connect, type HistoryProps as CoreHistoryProps, type HistoryWords } from '@ggary/core/history'
import { reactNormalizer } from '@ggary/core'

export interface HistoryProps extends CoreHistoryProps, Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
  /** The fixed text of the strip's name. */
  words?: Partial<HistoryWords>
}

/** What happened the last N times: one attempt, one mark, the latest at the end. */
export function History({ ticks, groups, label, size, locale, words, ...rest }: HistoryProps) {
  const api = connect({ ticks, groups, label, size, locale }, reactNormalizer, words)
  return (
    <div {...rest} {...api.rootProps}>
      <div {...api.stripProps}>
        {api.grouped
          ? api.groups.map((group) => (
              <span key={group.key} {...group.groupProps}>
                {group.ticks.map((tick) => (
                  <span key={tick.key} {...tick.tickProps} />
                ))}
              </span>
            ))
          : api.groups[0].ticks.map((tick) => <span key={tick.key} {...tick.tickProps} />)}
      </div>
      {api.axis && (
        <div {...api.axisProps}>
          {api.axisCells.map((cell) => (
            <span key={cell.key} {...cell.cellProps}>
              {cell.label}
            </span>
          ))}
        </div>
      )}
    </div>
  )
}

// packages/svelte/src/components/history/History.svelte
<script lang="ts">
  import { connect, type HistoryProps, type HistoryWords } from '@ggary/core/history'
  import { svelteNormalizer } from '@ggary/core'

  type Props = HistoryProps & {
    /** The fixed text of the strip's name. */
    words?: Partial<HistoryWords>
    [key: string]: unknown
  }

  /** What happened the last N times: one attempt, one mark, the latest at the end. */
  let { ticks, groups, label, size, locale, words, ...rest }: Props = $props()
  const api = $derived(connect({ ticks, groups, label, size, locale }, svelteNormalizer, { words }))
</script>

<div {...rest} {...api.rootProps}>
  <div {...api.stripProps}>
    {#if api.grouped}
      {#each api.groups as group (group.key)}<span {...group.groupProps}
          >{#each group.ticks as tick (tick.key)}<span {...tick.tickProps}></span>{/each}</span
        >{/each}
    {:else}
      {#each api.groups[0].ticks as tick (tick.key)}<span {...tick.tickProps}></span>{/each}
    {/if}
  </div>
  {#if api.axis}
    <div {...api.axisProps}>
      {#each api.axisCells as cell (cell.key)}<span {...cell.cellProps}>{cell.label}</span>{/each}
    </div>
  {/if}
</div>
