// packages/react/src/components/lanes/Lanes.tsx
import type { HTMLAttributes } from 'react'
import { connect, type LanesProps as CoreLanesProps, type LanesWords } from '@ggary/core/lanes'
import { reactNormalizer } from '@ggary/core'

export interface LanesProps extends CoreLanesProps, Omit<HTMLAttributes<HTMLUListElement>, 'children'> {
  /** The chart's fixed text: how a stretch is read, and the outcomes in words. */
  words?: LanesWords
}

export function Lanes({ lanes, label, start, end, locale, words, ...rest }: LanesProps) {
  const api = connect({ lanes, label, start, end, locale }, reactNormalizer, words)
  return (
    <ul {...rest} {...api.rootProps}>
      {api.lanes.map((lane) => (
        <li key={lane.key} {...lane.laneProps}>
          <span {...lane.labelProps}>{lane.lane.label}</span>
          <span {...lane.trackProps}>
            {lane.spans.map((span) => (
              <span key={span.key} {...span.spanProps} />
            ))}
          </span>
          <span {...api.laneTextProps}>{lane.text}</span>
        </li>
      ))}
    </ul>
  )
}

// packages/svelte/src/components/lanes/Lanes.svelte
<script lang="ts">
  import { connect, type LanesProps, type LanesWords } from '@ggary/core/lanes'
  import { svelteNormalizer } from '@ggary/core'

  type Props = LanesProps & {
    /** The chart's fixed text: how a stretch is read, and the outcomes in words. */
    words?: LanesWords
    [key: string]: unknown
  }

  let { lanes, label, start, end, locale, words, ...rest }: Props = $props()
  const api = $derived(connect({ lanes, label, start, end, locale }, svelteNormalizer, words))
</script>

<ul {...rest} {...api.rootProps}>
  {#each api.lanes as lane (lane.key)}
    <li {...lane.laneProps}>
      <span {...lane.labelProps}>{lane.lane.label}</span>
      <span {...lane.trackProps}>
        {#each lane.spans as span (span.key)}<span {...span.spanProps}></span>{/each}
      </span>
      <span {...api.laneTextProps}>{lane.text}</span>
    </li>
  {/each}
</ul>
