// packages/svelte/src/components/inserts/Inserts.svelte
<script lang="ts">
  import { connect, type InsertsProps } from '@ggary/core/inserts'
  import { svelteNormalizer } from '@ggary/core'

  type Props = InsertsProps & { [key: string]: unknown }

  let { items, target, onInsert, label, ...rest }: Props = $props()

  const api = $derived(connect({ items, target, onInsert, label }, svelteNormalizer))
</script>

<div {...api.rootProps} {...rest}>
  {#each api.items as item (item.value)}
    <button {...api.itemProps(item)}>{api.itemLabel(item)}</button>
  {/each}
</div>

// packages/react/src/components/inserts/Inserts.tsx
import type { HTMLAttributes } from 'react'
import { connect, type InsertsProps as CoreInsertsProps } from '@ggary/core/inserts'
import { reactNormalizer } from '@ggary/core'

export interface InsertsProps extends CoreInsertsProps, Omit<HTMLAttributes<HTMLDivElement>, 'onInsert'> {}

export function Inserts({ items, target, onInsert, label, ...rest }: InsertsProps) {
  const api = connect({ items, target, onInsert, label }, reactNormalizer)
  return (
    <div {...api.rootProps} {...rest}>
      {api.items.map((item) => (
        <button key={item.value} {...api.itemProps(item)}>
          {api.itemLabel(item)}
        </button>
      ))}
    </div>
  )
}
